// This file is auto-generated by @hey-api/openapi-ts
// Enhanced with Redux Toolkit authentication support

import axios from 'axios';
import { type ClientOptions, type Config, createClient, createConfig } from './client';
import type { ClientOptions as ClientOptions2 } from './types.gen';
import { getAuthToken, hasRefreshToken, isAccessTokenExpired } from '../utils/auth';

/**
 * The `createClientConfig()` function will be called on client initialization
 * and the returned object will become the client's initial configuration.
 *
 * You may want to initialize your client this way instead of calling
 * `setConfig()`. This is useful for example if you're using Next.js
 * to ensure your client always has the correct values.
 */
export type CreateClientConfig<T extends ClientOptions = ClientOptions2> = (
  override?: Config<ClientOptions & T>
) => Config<Required<ClientOptions> & T>;

// Get API base URL from environment, remove trailing slash to avoid double slashes
const getApiBaseUrl = () => {
  // In development, ALWAYS use relative path to leverage Vite proxy (same-origin = cookies work with SameSite="Lax")
  // This ensures cookies work even when frontend (localhost) and backend (127.0.0.1) are different origins
  if (import.meta.env.DEV) {
    return ''; // Empty string = relative path, will use Vite proxy at /api
  }
  
  // Production: use environment variable or fallback
  const envUrl =
    import.meta.env.VITE_API_BASE_URL ||
    "http://127.0.0.1:8000";
  // Remove trailing slash if present
  return envUrl.replace(/\/+$/, '');
};

// Create axios instance with interceptors
const axiosInstance = axios.create({
  baseURL: getApiBaseUrl(), // Base URL without trailing slash
  withCredentials: true, // Essential for cookie-based authentication
  headers: {
    'Content-Type': 'application/json',
  },
});

// Generous: a slow dev server (multipart submits, auto-reload) must not be mistaken for
// an invalid session. A timeout is treated as transient (request fails, session kept).
const REFRESH_TIMEOUT_MS = 20000;

/**
 * Dispatch the refresh thunk with a timeout guard. The thunk itself is single-flight
 * (see authSlice): concurrent callers - both interceptors, checkAuthStatus - all await
 * the SAME /refresh/ HTTP call. The backend rotates and blacklists refresh tokens on
 * every refresh, so two parallel refresh calls would present the same token twice and
 * the loser would get a 401 that used to clear the session and bounce the user to /login
 * (and from there to the default /admin/leads page).
 */
const refreshWithTimeout = async (): Promise<void> => {
  const { store } = await import('../store/store');
  const { refreshTokenAsync } = await import('../store/slices/authSlice');
  const refreshPromise = store.dispatch(refreshTokenAsync()).unwrap();
  const timeoutPromise = new Promise<never>((_, reject) =>
    setTimeout(() => reject(new Error('Refresh timeout')), REFRESH_TIMEOUT_MS)
  );
  await Promise.race([refreshPromise, timeoutPromise]);
};

// Request interceptor - add auth token and check expiration
// For localhost: Backend sets non-HTTP-only cookies which JavaScript can read.
// Tokens are stored in cookies and retrieved via getAuthToken() for the Authorization header.
axiosInstance.interceptors.request.use(
  async (config) => {
    // Skip token check for refresh, login, and logout endpoints
    const isRefreshEndpoint = config.url?.includes('/refresh/') || config.url?.includes('/accounts/refresh');
    const isAuthEndpoint = isRefreshEndpoint ||
                          config.url?.includes('/login') ||
                          config.url?.includes('/accounts/login') ||
                          config.url?.includes('/logout') ||
                          config.url?.includes('/accounts/logout');
    
    if (isAuthEndpoint) {
      // Do NOT send Authorization header for refresh: backend uses only the refresh_token cookie.
      // Sending an invalid access token would cause DRF's JWTAuthentication to return 401 before the view runs.
      if (!isRefreshEndpoint) {
        const token = getAuthToken();
        if (token) {
          config.headers.Authorization = `Bearer ${token}`;
        }
      }
      return config;
    }
    
    const token = getAuthToken();
    
    if (token) {
      // Check if token is expired or close to expiration
      if (isAccessTokenExpired(60000)) { // 1 minute buffer
        // Token is expired - proactively refresh before making the request.
        // Concurrent requests share the single in-flight refresh (single-flight thunk)
        // instead of going out with the stale token and 401ing mid-refresh.
        if (hasRefreshToken()) {
          try {
            await refreshWithTimeout();

            // Get the new token after refresh
            const newToken = getAuthToken();
            config.headers.Authorization = `Bearer ${newToken || token}`;
          } catch {
            // If refresh fails, still try with current token
            // The response interceptor will handle 401 if it fails
            config.headers.Authorization = `Bearer ${token}`;
          }
        } else {
          // No refresh token - use current token
          // Response interceptor will handle 401
          config.headers.Authorization = `Bearer ${token}`;
        }
      } else {
        // Token is still valid - use it
        config.headers.Authorization = `Bearer ${token}`;
      }
    } else if (!token && hasRefreshToken()) {
      // Access token cookie is gone (it expires after 15 min, src/utils/auth.ts) but the
      // refresh token is still present. Proactively refresh so we don't send an
      // unauthenticated request that would 401/403 and unmount the form.
      try {
        await refreshWithTimeout();

        // Attach the new token after refresh
        const newToken = getAuthToken();
        if (newToken) {
          config.headers.Authorization = `Bearer ${newToken}`;
        }
      } catch {
        // Refresh failed - send without token; the response interceptor handles the failure.
      }
    }

    // Detect FormData and remove Content-Type header
    // Axios will automatically set Content-Type: multipart/form-data with boundary
    if (config.data instanceof FormData) {
      delete config.headers['Content-Type'];
      delete config.headers['content-type'];
    }
    
    return config;
  },
  (error) => Promise.reject(error)
);

// Response interceptor - handle 401 and token refresh
const isMediaEndpoint = (url?: string) => url?.includes('/api/media/') ?? false;

// A 403 caused by an expired/absent access token (not a genuine permission denial,
// and not the deliberate inactive-user 403 from accounts/middleware.py). When true,
// the response interceptor should refresh-and-retry exactly as it does for a 401.
const isTokenExpiryError = (error: {
  response?: { status?: number; data?: { message?: string } };
}): boolean => {
  if (error.response?.status !== 403) return false;
  // When cookies are JS-readable (local dev), gate strictly: a still-valid access token or
  // a missing refresh token means this 403 is a genuine permission denial, not expiry.
  // In production cookies are HttpOnly (js-cookie sees nothing), so we can't inspect them -
  // allow the refresh attempt and let the server arbitrate (_retry prevents loops).
  if (getAuthToken()) {
    // Zero buffer keys on real expiry, not the 1-minute proactive buffer used by the request interceptor.
    if (!isAccessTokenExpired(0)) return false;
    if (!hasRefreshToken()) return false;
  }
  // Exclude the inactive-user 403 (body message contains "inactive").
  const message = error.response?.data?.message;
  if (typeof message === 'string' && message.toLowerCase().includes('inactive')) {
    return false;
  }
  return true;
};

axiosInstance.interceptors.response.use(
  (response) => response,
  async (error) => {
    const originalRequest = error.config;

    // Handle 401, or a 403 caused by token expiry, with a response (not network errors).
    // Genuine permission-denied 403s and the inactive-user 403 fail isTokenExpiryError and fall through.
    const status = error.response?.status;
    if ((status === 401 || (status === 403 && isTokenExpiryError(error))) && !originalRequest._retry) {
      const isAuthMeEndpoint = originalRequest.url?.includes('/auth/') && originalRequest.method?.toLowerCase() === 'get';
      const isRefreshEndpoint = originalRequest.url?.includes('/refresh/') || originalRequest.url?.includes('/accounts/refresh');
      const isLogoutEndpoint = originalRequest.url?.includes('/logout') || originalRequest.url?.includes('/accounts/logout');
      const isLoginEndpoint = originalRequest.url?.includes('/login');

      // GET /auth/ is used for credential-based auth check; let the thunk handle 401 (don't refresh or logout here)
      if (isAuthMeEndpoint) {
        return Promise.reject(error);
      }

      // Login failed (e.g. wrong password) - a refresh attempt makes no sense here
      if (isLoginEndpoint) {
        return Promise.reject(error);
      }

      // Media endpoints (upload URL, confirm, etc.): do not trigger global refresh/logout on 401
      if (isMediaEndpoint(originalRequest.url)) {
        return Promise.reject(error);
      }

      // Logout endpoint returned 401 - clear session
      if (isLogoutEndpoint) {
        const { store } = await import('../store/store');
        const { clearSessionAsync } = await import('../store/slices/authSlice');
        await store.dispatch(clearSessionAsync());
        return Promise.reject(error);
      }

      // Refresh endpoint returned 401 - do NOT clear or redirect (refresh token may still be valid).
      // Just reject so the request fails; user stays on page.
      if (isRefreshEndpoint) {
        return Promise.reject(error);
      }

      // NOTE: no hasRefreshToken() fast-fail here. In production the cookies are HttpOnly
      // (js-cookie can't see them), so that check logged users out on the first 401 even
      // though the browser held a valid refresh cookie. Attempt the refresh; if the cookie
      // is truly absent the server answers 401 and the authError path below clears session.

      originalRequest._retry = true;

      try {
        // Single-flight: if a refresh is already in flight (started by the request
        // interceptor or another 401), this awaits the SAME call instead of issuing a
        // second one, which token rotation + blacklist would reject with a 401.
        await refreshWithTimeout();

        return axiosInstance(originalRequest);
      } catch (refreshError) {
        // A competing refresh may have already installed a valid access token - the
        // failure was a lost race, not an expired session; just retry the request.
        if (getAuthToken() && !isAccessTokenExpired(0)) {
          return axiosInstance(originalRequest);
        }

        // Refresh failed - refreshTokenAsync rejects with { authError: true } ONLY when the
        // refresh endpoint itself answered 401/403. Everything else (timeout Error, 5xx,
        // network blip, unknown shape) is transient: fail this one request but KEEP the
        // session - clearing it here is what unmounted in-progress forms and bounced the
        // user through /login.
        const payload = refreshError as { networkError?: boolean; authError?: boolean; message?: string } | undefined;
        const isConfirmedAuthError = typeof payload === 'object' && payload != null && payload.authError === true;

        if (!isConfirmedAuthError) {
          return Promise.reject(refreshError);
        }

        // Server-confirmed auth error - clear access token and app state but keep refresh_token
        // cookie so we don't delete the refresh token when access token was being updated; next load can retry.
        if (import.meta.env.DEV) {
          console.error('[auth] clearing session: refresh endpoint rejected with', payload);
        }
        const { store } = await import('../store/store');
        const { clearSessionExceptRefreshTokenAsync } = await import('../store/slices/authSlice');
        await store.dispatch(clearSessionExceptRefreshTokenAsync());
        return Promise.reject(refreshError);
      }
    }

    // For non-401 errors or network errors, reject normally
    return Promise.reject(error);
  }
);

// Create and export the client
export const client = createClient(
  createConfig<ClientOptions2>({
    axios: axiosInstance,
    // Add auth callback so SDK can retrieve token for setAuthParams
    // This ensures the SDK's security configuration can access the token from cookies
    auth: () => getAuthToken() || undefined,
  })
);


