// This file is auto-generated by @hey-api/openapi-ts

export const AddressSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            readOnly: true
        },
        line1: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        line2: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        city: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        state: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        zipcode: {
            type: 'string',
            nullable: true,
            maxLength: 20
        },
        country: {
            type: 'string',
            nullable: true,
            maxLength: 255
        }
    },
    required: [
        'uuid'
    ]
} as const;

export const AgentCreateSchema = {
    type: 'object',
    properties: {
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            maxLength: 255
        },
        phone: {
            type: 'string',
            nullable: true
        },
        email: {
            type: 'string',
            format: 'email'
        }
    },
    required: [
        'email',
        'first_name',
        'last_name'
    ]
} as const;

export const AppointmentSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        lead: {
            type: 'integer',
            nullable: true
        },
        lead_uuid: {
            type: 'string',
            format: 'uuid'
        },
        referral_number: {
            type: 'string',
            readOnly: true
        },
        resident_name: {
            type: 'string',
            readOnly: true
        },
        avatar_url: {
            type: 'string',
            readOnly: true
        },
        resident_status: {
            type: 'string',
            readOnly: true
        },
        appointment_title: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        description: {
            type: 'string',
            nullable: true
        },
        appointment_date: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        appointment_time: {
            type: 'string',
            format: 'time',
            nullable: true
        },
        contact_type: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/ContactTypeEnum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        contact_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        contact_email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 254
        },
        status: {
            $ref: '#/components/schemas/AppointmentStatusEnum'
        },
        lead_detail: {
            allOf: [
                {
                    $ref: '#/components/schemas/LeadDetail'
                }
            ],
            readOnly: true
        },
        media: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/MediaMinimal'
            },
            readOnly: true
        },
        room: {
            type: 'string',
            readOnly: true
        },
        group_home: {
            type: 'string',
            readOnly: true
        },
        created_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        created_by_email: {
            type: 'string',
            format: 'email',
            readOnly: true
        },
        created_by_name: {
            type: 'string',
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        },
        deleted_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        action_note: {
            type: 'string',
            nullable: true
        },
        action_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        action_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        }
    },
    required: [
        'action_at',
        'action_by',
        'avatar_url',
        'created_at',
        'created_by',
        'created_by_email',
        'created_by_name',
        'group_home',
        'lead_detail',
        'media',
        'referral_number',
        'resident_name',
        'resident_status',
        'room',
        'updated_at',
        'uuid'
    ]
} as const;

export const AppointmentStatusEnumSchema = {
    enum: [
        'REQUESTED',
        'COMPLETED',
        'CANCELLED'
    ],
    type: 'string',
    description: '* `REQUESTED` - Requested\n* `COMPLETED` - Completed\n* `CANCELLED` - Cancelled'
} as const;

export const AssignmentCarePlanItemShiftSchema = {
    type: 'object',
    properties: {
        shift: {
            $ref: '#/components/schemas/ShiftEnum'
        }
    },
    required: [
        'shift'
    ]
} as const;

export const BlankEnumSchema = {
    enum: [
        ''
    ]
} as const;

export const CarePlanDailyLogSchema = {
    type: 'object',
    description: 'Serializer for ADL / Daily Tracking Goal logs\nPOST = UPSERT\nUniqueness:\n(care_plan_item + resident + log_date + shift)',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        care_plan_item_uuid: {
            type: 'string',
            format: 'uuid'
        },
        resident_uuid: {
            type: 'string'
        },
        log_date: {
            type: 'string',
            format: 'date'
        },
        shift: {
            $ref: '#/components/schemas/ShiftEnum'
        },
        status: {
            $ref: '#/components/schemas/CarePlanDailyLogStatusEnum'
        },
        note: {
            type: 'string',
            nullable: true
        },
        created_by: {
            type: 'integer',
            nullable: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'care_plan_item_uuid',
        'created_at',
        'log_date',
        'resident_uuid',
        'shift',
        'status',
        'updated_at',
        'uuid'
    ]
} as const;

export const CarePlanDailyLogStatusEnumSchema = {
    enum: [
        'WORKED',
        'DID_NOT_WORK',
        'COULD_NOT_WORK'
    ],
    type: 'string',
    description: '* `WORKED` - Worked\n* `DID_NOT_WORK` - Did Not Work\n* `COULD_NOT_WORK` - Could Not Work'
} as const;

export const CarePlanItemSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        resident: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/Type094Enum'
        },
        title: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        description: {
            type: 'string',
            nullable: true
        },
        created_by: {
            type: 'string',
            nullable: true
        },
        assigned_shifts: {
            type: 'string',
            readOnly: true
        },
        is_archived: {
            type: 'string',
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'assigned_shifts',
        'created_at',
        'is_archived',
        'resident',
        'type',
        'updated_at',
        'uuid'
    ]
} as const;

export const CarePlanItemListSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        type: {
            $ref: '#/components/schemas/Type094Enum'
        },
        title: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        description: {
            type: 'string',
            nullable: true
        },
        assigned_shifts: {
            type: 'string',
            readOnly: true
        },
        daily_status: {
            type: 'string',
            readOnly: true
        },
        monthly_progress: {
            type: 'string',
            readOnly: true
        },
        created_by_details: {
            type: 'string',
            readOnly: true
        },
        updated_by_details: {
            type: 'string',
            readOnly: true
        },
        is_archived: {
            type: 'string',
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        deleted_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        }
    },
    required: [
        'assigned_shifts',
        'created_at',
        'created_by_details',
        'daily_status',
        'is_archived',
        'monthly_progress',
        'type',
        'updated_at',
        'updated_by_details',
        'uuid'
    ]
} as const;

export const CarePlanReportSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        resident_uuid: {
            type: 'string'
        },
        report_month: {
            type: 'integer',
            maximum: 32767,
            minimum: 0
        },
        report_year: {
            type: 'integer',
            maximum: 32767,
            minimum: 0
        },
        report_data: {},
        generated_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        pdf_url: {
            type: 'string',
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'created_at',
        'generated_by',
        'pdf_url',
        'report_data',
        'report_month',
        'report_year',
        'resident_uuid',
        'updated_at',
        'uuid'
    ]
} as const;

export const CompleteOnboardingSchema = {
    type: 'object',
    properties: {
        group_home: {
            type: 'string',
            format: 'uuid'
        },
        room: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        check_in_date: {
            type: 'string',
            format: 'date'
        }
    },
    required: [
        'check_in_date',
        'group_home'
    ]
} as const;

export const ConsentFormCreateSchema = {
    type: 'object',
    properties: {
        resident_uuid: {
            type: 'string',
            format: 'uuid'
        },
        form_name: {
            type: 'string',
            maxLength: 255
        },
        form_code: {
            type: 'string',
            maxLength: 100
        },
        frequency_type: {
            type: 'string',
            maxLength: 20
        },
        status: {
            $ref: '#/components/schemas/ConsentFormCreateStatusEnum'
        },
        form_json: {},
        signer_type: {
            type: 'string',
            nullable: true,
            maxLength: 20
        },
        next_due_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        }
    },
    required: [
        'form_code',
        'form_name',
        'frequency_type',
        'resident_uuid',
        'status'
    ]
} as const;

export const ConsentFormCreateStatusEnumSchema = {
    enum: [
        'DRAFT',
        'COMPLETED',
        'SIGNED'
    ],
    type: 'string',
    description: '* `DRAFT` - DRAFT\n* `COMPLETED` - COMPLETED\n* `SIGNED` - SIGNED'
} as const;

export const ConsentFormEntrySchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        form_uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        version: {
            type: 'string',
            maxLength: 50
        },
        form_json: {},
        filled_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        next_due_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/ConsentFormEntryStatusEnum'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        }
    },
    required: [
        'form_json',
        'form_uuid',
        'status',
        'uuid',
        'version'
    ]
} as const;

export const ConsentFormEntryStatusEnumSchema = {
    enum: [
        'DRAFT',
        'COMPLETED',
        'SIGNED'
    ],
    type: 'string',
    description: '* `DRAFT` - Draft\n* `COMPLETED` - Completed\n* `SIGNED` - Signed'
} as const;

export const ConsentFormShareSchema = {
    type: 'object',
    properties: {
        recipient_email: {
            type: 'string',
            format: 'email'
        },
        recipient_name: {
            type: 'string',
            maxLength: 255
        },
        media_uuid: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        html_content: {
            type: 'string',
            nullable: true,
            description: 'HTML string to convert to PDF on the server. If provided, backend generates PDF, uploads to S3, and creates a Media record automatically.'
        },
        recipient_type: {
            nullable: true,
            description: 'Portal role to share with. Stamps ConsentForm.signer_type so the document is visible ONLY in the matching portal.\n\n* `GUARDIAN` - Guardian\n* `AGENT` - Agent',
            oneOf: [
                {
                    $ref: '#/components/schemas/RecipientTypeEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        }
    },
    required: [
        'recipient_email',
        'recipient_name'
    ]
} as const;

export const ContactTypeEnumSchema = {
    enum: [
        'PROVIDER',
        'GUARDIAN',
        'OTHER'
    ],
    type: 'string',
    description: '* `PROVIDER` - Provider\n* `GUARDIAN` - Guardian\n* `OTHER` - Other'
} as const;

export const FileTypeEnumSchema = {
    enum: [
        'image',
        'document',
        'video',
        'audio',
        'other'
    ],
    type: 'string',
    description: '* `image` - Image\n* `document` - Document\n* `video` - Video\n* `audio` - Audio\n* `other` - Other'
} as const;

export const GenderEnumSchema = {
    enum: [
        'MALE',
        'FEMALE',
        'OTHER',
        'UNKNOWN'
    ],
    type: 'string',
    description: '* `MALE` - Male\n* `FEMALE` - Female\n* `OTHER` - Other\n* `UNKNOWN` - Unknown'
} as const;

export const GroupHomeSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 255
        },
        timezone: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/TimezoneEnum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        phone: {
            type: 'string',
            maxLength: 20
        },
        fax: {
            type: 'string',
            maxLength: 20
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true
        },
        emergency_contact_number: {
            type: 'string',
            nullable: true,
            maxLength: 20
        },
        address: {
            $ref: '#/components/schemas/Address'
        },
        license: {
            $ref: '#/components/schemas/License'
        },
        no_of_rooms: {
            type: 'integer',
            maximum: 9223372036854776000,
            minimum: -9223372036854776000,
            format: 'int64'
        },
        active: {
            type: 'boolean'
        },
        shifts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/GroupHomeShift'
            }
        },
        rooms: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/GroupHomeRoom'
            },
            readOnly: true
        },
        media: {
            type: 'string',
            readOnly: true
        },
        avatar_url: {
            type: 'string',
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        }
    },
    required: [
        'avatar_url',
        'created_at',
        'fax',
        'media',
        'name',
        'no_of_rooms',
        'phone',
        'rooms',
        'updated_at',
        'uuid'
    ]
} as const;

export const GroupHomeRoomSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        room_number: {
            type: 'string',
            maxLength: 50
        },
        is_active: {
            type: 'boolean'
        },
        is_occupied: {
            type: 'boolean'
        }
    },
    required: [
        'room_number',
        'uuid'
    ]
} as const;

export const GroupHomeShiftSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        shift: {
            $ref: '#/components/schemas/ShiftEnum'
        },
        start_time: {
            type: 'string',
            format: 'time'
        },
        end_time: {
            type: 'string',
            format: 'time'
        },
        is_active: {
            type: 'boolean'
        }
    },
    required: [
        'end_time',
        'shift',
        'start_time',
        'uuid'
    ]
} as const;

export const GroupHomeStatusSchema = {
    type: 'object',
    properties: {
        active: {
            type: 'boolean'
        }
    }
} as const;

export const GroupHomeUserSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            readOnly: true
        },
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 255
        },
        phone: {
            type: 'integer',
            maximum: 9223372036854776000,
            minimum: -9223372036854776000,
            format: 'int64',
            nullable: true
        },
        role: {
            type: 'string',
            readOnly: true
        },
        active: {
            type: 'boolean'
        },
        last_login: {
            type: 'string',
            format: 'date-time',
            nullable: true
        }
    },
    required: [
        'email',
        'first_name',
        'role',
        'uuid'
    ]
} as const;

export const GuardianCreateSchema = {
    type: 'object',
    properties: {
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            maxLength: 255
        },
        phone: {
            type: 'string',
            nullable: true
        },
        email: {
            type: 'string',
            format: 'email'
        }
    },
    required: [
        'email',
        'first_name',
        'last_name'
    ]
} as const;

export const IncidentSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        incident_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        resident: {
            type: 'string'
        },
        resident_uuid: {
            type: 'string',
            readOnly: true
        },
        reported_by: {
            type: 'string',
            nullable: true
        },
        location: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        region: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        received_date: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        incident_datetime: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        agency_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        pre_incident_notes: {
            type: 'string',
            nullable: true
        },
        incident_description: {
            type: 'string',
            nullable: true
        },
        response_action: {
            type: 'string',
            nullable: true
        },
        send_notification: {
            type: 'boolean'
        },
        status: {
            allOf: [
                {
                    $ref: '#/components/schemas/IncidentStatusEnum'
                }
            ],
            readOnly: true
        },
        lead_uuid: {
            type: 'string',
            readOnly: true
        },
        referral_number: {
            type: 'string',
            readOnly: true
        },
        signature_url: {
            type: 'string',
            readOnly: true
        },
        resident_details: {
            allOf: [
                {
                    $ref: '#/components/schemas/IncidentResidentDetails'
                }
            ],
            readOnly: true
        },
        resident_status: {
            type: 'string',
            readOnly: true
        },
        reported_by_details: {
            allOf: [
                {
                    $ref: '#/components/schemas/IncidentUser'
                }
            ],
            readOnly: true
        },
        notifications: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/IncidentNotification'
            },
            readOnly: true
        },
        comments: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/IncidentComment'
            },
            readOnly: true
        },
        medical_flags: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/IncidentMedicalFlag'
            }
        },
        legal_flags: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/IncidentLegalFlag'
            }
        },
        social_flags: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/IncidentSocialFlag'
            }
        },
        victim_flags: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/IncidentVictimFlag'
            }
        },
        signature: {
            type: 'string',
            readOnly: true
        },
        group_home: {
            type: 'string',
            readOnly: true
        },
        assigned_program_manager: {
            type: 'string',
            readOnly: true
        },
        program_manager_email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 254
        },
        coordinator_email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 254
        },
        reporter_signature_url: {
            type: 'string',
            readOnly: true
        },
        pm_signature_url: {
            type: 'string',
            readOnly: true
        },
        pm_signature: {
            type: 'string',
            readOnly: true
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        },
        submitted_for_review_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        },
        completed_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        },
        pm_review_notes: {
            type: 'string',
            nullable: true
        },
        pm_program_type: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        pm_service_transition: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/PmServiceTransitionEnum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        pm_service_transition_description: {
            type: 'string',
            nullable: true
        },
        pm_behavior_plan_followed: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/PmBehaviorPlanFollowedEnum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        pm_title: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        edits: {
            type: 'string',
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'assigned_program_manager',
        'comments',
        'completed_at',
        'edits',
        'group_home',
        'lead_uuid',
        'notifications',
        'pm_signature',
        'pm_signature_url',
        'referral_number',
        'reported_by_details',
        'reporter_signature_url',
        'resident',
        'resident_details',
        'resident_status',
        'resident_uuid',
        'signature',
        'signature_url',
        'started_at',
        'status',
        'submitted_for_review_at',
        'updated_at',
        'uuid'
    ]
} as const;

export const IncidentCommentSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        comment: {
            type: 'string'
        },
        role_name: {
            type: 'string',
            readOnly: true
        },
        created_by_name: {
            type: 'string',
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'comment',
        'created_at',
        'created_by_name',
        'role_name',
        'uuid'
    ]
} as const;

export const IncidentLegalFlagSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        legal_type: {
            type: 'string',
            maxLength: 255
        }
    },
    required: [
        'legal_type',
        'uuid'
    ]
} as const;

export const IncidentMedicalFlagSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        medical_type: {
            type: 'string',
            maxLength: 255
        },
        medical_other_details: {
            type: 'string'
        }
    },
    required: [
        'medical_type',
        'uuid'
    ]
} as const;

export const IncidentNotificationSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        incident: {
            type: 'integer'
        },
        type: {
            $ref: '#/components/schemas/IncidentNotificationTypeEnum'
        },
        user: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        user_name: {
            type: 'string',
            readOnly: true
        },
        user_email: {
            type: 'string',
            readOnly: true
        },
        notify: {
            type: 'boolean'
        },
        notify_date: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        notify_time: {
            type: 'string',
            format: 'time',
            nullable: true
        },
        method_of_contact: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        by_whom: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'incident',
        'type',
        'updated_at',
        'user',
        'user_email',
        'user_name',
        'uuid'
    ]
} as const;

export const IncidentNotificationTypeEnumSchema = {
    enum: [
        'STAFF',
        'SERVICE_COORDINATOR',
        'PROGRAM_MANAGER',
        'GUARDIAN',
        'AGENT',
        'NURSING',
        'ADDITIONAL_SERVICE_PROVIDER'
    ],
    type: 'string',
    description: '* `STAFF` - Staff\n* `SERVICE_COORDINATOR` - Service Coordinator\n* `PROGRAM_MANAGER` - Program Manager\n* `GUARDIAN` - Guardian\n* `AGENT` - Agent\n* `NURSING` - Nursing\n* `ADDITIONAL_SERVICE_PROVIDER` - Additional Service Provider'
} as const;

export const IncidentResidentDetailsSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            readOnly: true
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 255
        },
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        avatar_url: {
            type: 'string',
            readOnly: true
        },
        lead_uuid: {
            type: 'string',
            readOnly: true
        },
        group_home: {
            type: 'string',
            readOnly: true
        },
        date_of_birth: {
            type: 'string',
            readOnly: true
        }
    },
    required: [
        'avatar_url',
        'date_of_birth',
        'email',
        'first_name',
        'group_home',
        'lead_uuid',
        'uuid'
    ]
} as const;

export const IncidentSocialFlagSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        social_type: {
            type: 'string',
            maxLength: 255
        },
        social_other_details: {
            type: 'string'
        }
    },
    required: [
        'social_type',
        'uuid'
    ]
} as const;

export const IncidentStatusEnumSchema = {
    enum: [
        'DRAFT',
        'IN_PROGRESS',
        'PM_REVIEW_PENDING',
        'COMPLETED',
        'ACKNOWLEDGED'
    ],
    type: 'string',
    description: '* `DRAFT` - Draft\n* `IN_PROGRESS` - In Progress\n* `PM_REVIEW_PENDING` - Program Manager Review Pending\n* `COMPLETED` - Completed\n* `ACKNOWLEDGED` - Acknowledged'
} as const;

export const IncidentUserSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            readOnly: true
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 255
        },
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        avatar_url: {
            type: 'string',
            readOnly: true
        },
        role: {
            type: 'string',
            readOnly: true
        }
    },
    required: [
        'avatar_url',
        'email',
        'first_name',
        'role',
        'uuid'
    ]
} as const;

export const IncidentVictimFlagSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        victim_type: {
            type: 'string',
            maxLength: 255
        }
    },
    required: [
        'uuid',
        'victim_type'
    ]
} as const;

export const InsuranceCreateSchema = {
    type: 'object',
    properties: {
        provider: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        policy_number: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        status: {
            type: 'boolean',
            nullable: true
        }
    }
} as const;

export const LeadSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        referral_number: {
            type: 'string',
            readOnly: true
        },
        user: {
            type: 'integer'
        },
        guardian: {
            type: 'integer',
            nullable: true
        },
        agent: {
            type: 'integer',
            nullable: true
        },
        guardian_relation: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        address: {
            type: 'integer',
            nullable: true
        },
        date_of_birth: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        gender: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/GenderEnum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        referral_source: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        status: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/Status7b0Enum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        reason: {
            type: 'string',
            nullable: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        }
    },
    required: [
        'created_at',
        'referral_number',
        'updated_at',
        'user',
        'uuid'
    ]
} as const;

export const LeadCreateSchema = {
    type: 'object',
    properties: {
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            maxLength: 255
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true
        },
        phone: {
            type: 'integer',
            nullable: true
        },
        guardian: {
            $ref: '#/components/schemas/GuardianCreate'
        },
        guardian_uuid: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        agent: {
            $ref: '#/components/schemas/AgentCreate'
        },
        agent_uuid: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        address: {
            $ref: '#/components/schemas/Address'
        },
        date_of_birth: {
            type: 'string',
            format: 'date'
        },
        gender: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/GenderEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        referral_source: {
            type: 'string',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/Status7b0Enum'
        },
        guardian_relation: {
            type: 'string',
            nullable: true
        },
        documents_checklist_complete: {
            type: 'boolean',
            default: false
        },
        insurance: {
            $ref: '#/components/schemas/InsuranceCreate'
        }
    },
    required: [
        'first_name',
        'last_name'
    ]
} as const;

export const LeadDetailSchema = {
    type: 'object',
    properties: {
        guardian_relation: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        date_of_birth: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        gender: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/GenderEnum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        referral_source: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        status: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/Status7b0Enum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        reason: {
            type: 'string',
            nullable: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        },
        user: {
            type: 'integer'
        },
        guardian: {
            type: 'integer',
            nullable: true
        },
        agent: {
            type: 'integer',
            nullable: true
        },
        address: {
            type: 'integer',
            nullable: true
        }
    },
    required: [
        'created_at',
        'updated_at',
        'user',
        'uuid'
    ]
} as const;

export const LicenseSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        number: {
            type: 'string',
            maxLength: 255
        },
        start_date: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        expiry_date: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true,
            nullable: true
        }
    },
    required: [
        'created_at',
        'number',
        'updated_at',
        'uuid'
    ]
} as const;

export const LoginSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email'
        }
    },
    required: [
        'email'
    ]
} as const;

export const MediaSchema = {
    type: 'object',
    description: 'Serializer for retrieving media information',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        file_url: {
            type: 'string',
            readOnly: true
        },
        original_filename: {
            type: 'string',
            readOnly: true
        },
        file_type: {
            allOf: [
                {
                    $ref: '#/components/schemas/FileTypeEnum'
                }
            ],
            readOnly: true
        },
        mime_type: {
            type: 'string',
            readOnly: true
        },
        file_extension: {
            type: 'string',
            readOnly: true
        },
        file_size: {
            type: 'integer',
            readOnly: true,
            description: 'File size in bytes'
        },
        width: {
            type: 'integer',
            readOnly: true,
            nullable: true,
            description: 'Image width in pixels'
        },
        height: {
            type: 'integer',
            readOnly: true,
            nullable: true,
            description: 'Image height in pixels'
        },
        alt_text: {
            type: 'string',
            readOnly: true,
            nullable: true
        },
        description: {
            type: 'string',
            readOnly: true,
            nullable: true
        },
        status: {
            allOf: [
                {
                    $ref: '#/components/schemas/Status71dEnum'
                }
            ],
            readOnly: true
        },
        metadata: {
            readOnly: true,
            description: 'Extra metadata like signing info'
        },
        signed: {
            type: 'string',
            readOnly: true
        },
        uploaded_by: {
            type: 'string',
            readOnly: true
        },
        uploaded_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'alt_text',
        'description',
        'file_extension',
        'file_size',
        'file_type',
        'file_url',
        'height',
        'id',
        'metadata',
        'mime_type',
        'original_filename',
        'signed',
        'status',
        'updated_at',
        'uploaded_at',
        'uploaded_by',
        'width'
    ]
} as const;

export const MediaListSchema = {
    type: 'object',
    description: 'Lighter serializer for list views',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        file_url: {
            type: 'string',
            readOnly: true
        },
        original_filename: {
            type: 'string',
            maxLength: 255
        },
        file_type: {
            $ref: '#/components/schemas/FileTypeEnum'
        },
        mime_type: {
            type: 'string',
            maxLength: 100
        },
        file_extension: {
            type: 'string',
            maxLength: 10
        },
        file_size: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0,
            description: 'File size in bytes'
        },
        width: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0,
            nullable: true,
            description: 'Image width in pixels'
        },
        height: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0,
            nullable: true,
            description: 'Image height in pixels'
        },
        alt_text: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        description: {
            type: 'string',
            readOnly: true
        },
        status: {
            $ref: '#/components/schemas/Status71dEnum'
        },
        metadata: {
            description: 'Extra metadata like signing info'
        },
        uploaded_by: {
            type: 'integer',
            nullable: true
        },
        uploaded_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'description',
        'file_extension',
        'file_size',
        'file_type',
        'file_url',
        'id',
        'mime_type',
        'original_filename',
        'updated_at',
        'uploaded_at'
    ]
} as const;

export const MediaMinimalSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        file_url: {
            type: 'string',
            readOnly: true
        },
        original_filename: {
            type: 'string',
            maxLength: 255
        },
        file_type: {
            $ref: '#/components/schemas/FileTypeEnum'
        },
        mime_type: {
            type: 'string',
            maxLength: 100
        },
        file_extension: {
            type: 'string',
            maxLength: 10
        },
        file_size: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0,
            description: 'File size in bytes'
        },
        alt_text: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        description: {
            type: 'string',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/Status71dEnum'
        },
        metadata: {
            description: 'Extra metadata like signing info'
        },
        uploaded_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'file_extension',
        'file_size',
        'file_type',
        'file_url',
        'id',
        'mime_type',
        'original_filename',
        'uploaded_at'
    ]
} as const;

export const NullEnumSchema = {
    enum: [
        null
    ]
} as const;

export const PaginatedMediaListListSchema = {
    type: 'object',
    required: [
        'count',
        'results'
    ],
    properties: {
        count: {
            type: 'integer',
            example: 123
        },
        next: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=4'
        },
        previous: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=2'
        },
        results: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/MediaList'
            }
        }
    }
} as const;

export const PatchedChangePasswordSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const PatchedGroupHomeStatusSchema = {
    type: 'object',
    properties: {
        active: {
            type: 'boolean'
        }
    }
} as const;

export const PatchedMoveOutSchema = {
    type: 'object',
    properties: {
        check_out_date: {
            type: 'string',
            format: 'date'
        },
        reason: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const PatchedRejectReferralSchema = {
    type: 'object',
    properties: {
        reason: {
            type: 'string',
            description: 'Reason for rejecting the referral'
        }
    }
} as const;

export const PatchedUserSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            readOnly: true
        },
        username: {
            type: 'string',
            maxLength: 150
        },
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 255
        },
        phone: {
            type: 'integer',
            maximum: 9223372036854776000,
            minimum: -9223372036854776000,
            format: 'int64',
            nullable: true
        },
        ssn: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        npi: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        active: {
            type: 'boolean'
        },
        role: {
            allOf: [
                {
                    $ref: '#/components/schemas/Role'
                }
            ],
            readOnly: true
        },
        group_home: {
            type: 'string',
            readOnly: true
        },
        group_homes: {
            type: 'string',
            readOnly: true
        },
        avatar_url: {
            type: 'string',
            readOnly: true
        },
        signature_url: {
            type: 'string',
            readOnly: true
        },
        signature_alt_text: {
            type: 'string',
            readOnly: true
        },
        isPasswordSet: {
            type: 'string',
            readOnly: true
        },
        permissions: {
            type: 'string',
            readOnly: true
        }
    }
} as const;

export const PmBehaviorPlanFollowedEnumSchema = {
    enum: [
        'YES',
        'NO',
        'N_A'
    ],
    type: 'string',
    description: '* `YES` - Yes\n* `NO` - No\n* `N_A` - N/A'
} as const;

export const PmServiceTransitionEnumSchema = {
    enum: [
        'YES',
        'NO'
    ],
    type: 'string',
    description: '* `YES` - Yes\n* `NO` - No'
} as const;

export const ProviderSchema = {
    type: 'object',
    description: 'Full serializer for create / update / retrieve operations.\nAccepts `lead_uuid` on write; exposes it on read.',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        lead_uuid: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        name: {
            type: 'string',
            maxLength: 255
        },
        specialty: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 254
        },
        address: {
            type: 'string',
            nullable: true
        },
        phone_number: {
            type: 'string',
            nullable: true,
            maxLength: 30
        },
        fax_number: {
            type: 'string',
            nullable: true,
            maxLength: 30
        },
        created_by: {
            type: 'integer',
            readOnly: true,
            nullable: true
        },
        created_by_name: {
            type: 'string',
            readOnly: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: [
        'created_at',
        'created_by',
        'created_by_name',
        'name',
        'updated_at',
        'uuid'
    ]
} as const;

export const ReAdmitSchema = {
    type: 'object',
    properties: {
        status: {
            allOf: [
                {
                    $ref: '#/components/schemas/ReAdmitStatusEnum'
                }
            ],
            default: 'ACTIVE'
        },
        room: {
            type: 'string',
            format: 'uuid'
        },
        group_home_uuid: {
            type: 'string',
            format: 'uuid'
        },
        check_in_date: {
            type: 'string',
            format: 'date'
        },
        financial_effective_date: {
            type: 'string',
            format: 'date',
            nullable: true
        }
    },
    required: [
        'check_in_date',
        'group_home_uuid',
        'room'
    ]
} as const;

export const ReAdmitStatusEnumSchema = {
    enum: [
        'ACTIVE',
        'ASSIGNED'
    ],
    type: 'string',
    description: '* `ACTIVE` - ACTIVE\n* `ASSIGNED` - ASSIGNED'
} as const;

export const RecipientTypeEnumSchema = {
    enum: [
        'GUARDIAN',
        'AGENT'
    ],
    type: 'string',
    description: '* `GUARDIAN` - Guardian\n* `AGENT` - Agent'
} as const;

export const RegisterSchema = {
    type: 'object',
    description: 'Username is generated by the backend (random); do not send from client.',
    properties: {
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            maxLength: 255
        },
        email: {
            type: 'string',
            format: 'email'
        },
        phone: {
            type: 'integer',
            nullable: true
        },
        ssn: {
            type: 'string',
            nullable: true
        },
        npi: {
            type: 'string',
            nullable: true
        }
    },
    required: [
        'email',
        'first_name',
        'last_name'
    ]
} as const;

export const RoleSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 255
        },
        type: {
            type: 'string',
            maxLength: 50
        }
    },
    required: [
        'name',
        'type',
        'uuid'
    ]
} as const;

export const RoleWithPermissionsSchema = {
    type: 'object',
    description: 'Role with its full permission list — used in admin settings view.',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            readOnly: true
        },
        name: {
            type: 'string',
            readOnly: true
        },
        type: {
            type: 'string',
            readOnly: true
        },
        description: {
            type: 'string',
            readOnly: true,
            nullable: true
        },
        permissions: {
            type: 'string',
            readOnly: true
        }
    },
    required: [
        'description',
        'name',
        'permissions',
        'type',
        'uuid'
    ]
} as const;

export const SetPasswordSchema = {
    type: 'object',
    properties: {
        password: {
            type: 'string',
            minLength: 8
        }
    },
    required: [
        'password'
    ]
} as const;

export const ShiftEnumSchema = {
    enum: [
        'MORNING',
        'EVENING',
        'NIGHT'
    ],
    type: 'string',
    description: '* `MORNING` - Morning\n* `EVENING` - Evening\n* `NIGHT` - Night'
} as const;

export const Status71dEnumSchema = {
    enum: [
        'active',
        'deleted',
        'archived'
    ],
    type: 'string',
    description: '* `active` - Active\n* `deleted` - Deleted\n* `archived` - Archived'
} as const;

export const Status7b0EnumSchema = {
    enum: [
        'DRAFT',
        'UNDER_REVIEW',
        'DOCS_PENDING',
        'ONBOARDING_IN_PROGRESS',
        'COMPLETED',
        'REJECTED'
    ],
    type: 'string',
    description: '* `DRAFT` - Draft\n* `UNDER_REVIEW` - Under Review\n* `DOCS_PENDING` - Docs Pending\n* `ONBOARDING_IN_PROGRESS` - Onboarding In Progress\n* `COMPLETED` - Completed\n* `REJECTED` - Rejected'
} as const;

export const TimezoneEnumSchema = {
    enum: [
        'Eastern Time',
        'Central Time',
        'Mountain Time',
        'Pacific Time',
        'Arizona Time',
        'Alaska Time'
    ],
    type: 'string',
    description: '* `Eastern Time` - Eastern Time\n* `Central Time` - Central Time\n* `Mountain Time` - Mountain Time\n* `Pacific Time` - Pacific Time\n* `Arizona Time` - Arizona Time\n* `Alaska Time` - Alaska Time'
} as const;

export const TransferResidentSchema = {
    type: 'object',
    properties: {
        group_home: {
            type: 'string',
            format: 'uuid'
        },
        room: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        check_in_date: {
            type: 'string',
            format: 'date'
        }
    },
    required: [
        'check_in_date',
        'group_home'
    ]
} as const;

export const Type094EnumSchema = {
    enum: [
        'ADL',
        'GOAL'
    ],
    type: 'string',
    description: '* `ADL` - ADL\n* `GOAL` - Goal'
} as const;

export const UserSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            readOnly: true
        },
        username: {
            type: 'string',
            maxLength: 150
        },
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 255
        },
        phone: {
            type: 'integer',
            maximum: 9223372036854776000,
            minimum: -9223372036854776000,
            format: 'int64',
            nullable: true
        },
        ssn: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        npi: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        active: {
            type: 'boolean'
        },
        role: {
            allOf: [
                {
                    $ref: '#/components/schemas/Role'
                }
            ],
            readOnly: true
        },
        group_home: {
            type: 'string',
            readOnly: true
        },
        group_homes: {
            type: 'string',
            readOnly: true
        },
        avatar_url: {
            type: 'string',
            readOnly: true
        },
        signature_url: {
            type: 'string',
            readOnly: true
        },
        signature_alt_text: {
            type: 'string',
            readOnly: true
        },
        isPasswordSet: {
            type: 'string',
            readOnly: true
        },
        permissions: {
            type: 'string',
            readOnly: true
        }
    },
    required: [
        'avatar_url',
        'email',
        'first_name',
        'group_home',
        'group_homes',
        'isPasswordSet',
        'permissions',
        'role',
        'signature_alt_text',
        'signature_url',
        'username',
        'uuid'
    ]
} as const;

export const VerifyOTPSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email'
        },
        otp: {
            type: 'string',
            maxLength: 6,
            minLength: 6
        }
    },
    required: [
        'email',
        'otp'
    ]
} as const;

export const AddressWritableSchema = {
    type: 'object',
    properties: {
        line1: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        line2: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        city: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        state: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        zipcode: {
            type: 'string',
            nullable: true,
            maxLength: 20
        },
        country: {
            type: 'string',
            nullable: true,
            maxLength: 255
        }
    }
} as const;

export const AppointmentWritableSchema = {
    type: 'object',
    properties: {
        lead: {
            type: 'integer',
            nullable: true
        },
        lead_uuid: {
            type: 'string',
            format: 'uuid'
        },
        appointment_title: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        description: {
            type: 'string',
            nullable: true
        },
        appointment_date: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        appointment_time: {
            type: 'string',
            format: 'time',
            nullable: true
        },
        contact_type: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/ContactTypeEnum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        contact_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        contact_email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 254
        },
        status: {
            $ref: '#/components/schemas/AppointmentStatusEnum'
        },
        deleted_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        action_note: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const CarePlanDailyLogWritableSchema = {
    type: 'object',
    description: 'Serializer for ADL / Daily Tracking Goal logs\nPOST = UPSERT\nUniqueness:\n(care_plan_item + resident + log_date + shift)',
    properties: {
        care_plan_item_uuid: {
            type: 'string',
            format: 'uuid'
        },
        resident_uuid: {
            type: 'string'
        },
        log_date: {
            type: 'string',
            format: 'date'
        },
        shift: {
            $ref: '#/components/schemas/ShiftEnum'
        },
        status: {
            $ref: '#/components/schemas/CarePlanDailyLogStatusEnum'
        },
        note: {
            type: 'string',
            nullable: true
        },
        created_by: {
            type: 'integer',
            nullable: true
        }
    },
    required: [
        'care_plan_item_uuid',
        'log_date',
        'resident_uuid',
        'shift',
        'status'
    ]
} as const;

export const CarePlanItemWritableSchema = {
    type: 'object',
    properties: {
        resident: {
            type: 'string'
        },
        type: {
            $ref: '#/components/schemas/Type094Enum'
        },
        title: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        description: {
            type: 'string',
            nullable: true
        },
        created_by: {
            type: 'string',
            nullable: true
        },
        shifts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/AssignmentCarePlanItemShift'
            },
            writeOnly: true
        }
    },
    required: [
        'resident',
        'type'
    ]
} as const;

export const CarePlanItemListWritableSchema = {
    type: 'object',
    properties: {
        type: {
            $ref: '#/components/schemas/Type094Enum'
        },
        title: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        description: {
            type: 'string',
            nullable: true
        },
        deleted_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        }
    },
    required: [
        'type'
    ]
} as const;

export const CarePlanReportWritableSchema = {
    type: 'object',
    properties: {
        resident_uuid: {
            type: 'string'
        },
        report_month: {
            type: 'integer',
            maximum: 32767,
            minimum: 0
        },
        report_year: {
            type: 'integer',
            maximum: 32767,
            minimum: 0
        },
        report_data: {}
    },
    required: [
        'report_data',
        'report_month',
        'report_year',
        'resident_uuid'
    ]
} as const;

export const ConsentFormEntryWritableSchema = {
    type: 'object',
    properties: {
        version: {
            type: 'string',
            maxLength: 50
        },
        form_json: {},
        filled_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        next_due_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/ConsentFormEntryStatusEnum'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            nullable: true
        }
    },
    required: [
        'form_json',
        'status',
        'version'
    ]
} as const;

export const GroupHomeWritableSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 255
        },
        timezone: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/TimezoneEnum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        phone: {
            type: 'string',
            maxLength: 20
        },
        fax: {
            type: 'string',
            maxLength: 20
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true
        },
        emergency_contact_number: {
            type: 'string',
            nullable: true,
            maxLength: 20
        },
        address: {
            $ref: '#/components/schemas/AddressWritable'
        },
        license: {
            $ref: '#/components/schemas/LicenseWritable'
        },
        no_of_rooms: {
            type: 'integer',
            maximum: 9223372036854776000,
            minimum: -9223372036854776000,
            format: 'int64'
        },
        active: {
            type: 'boolean'
        },
        shifts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/GroupHomeShiftWritable'
            }
        },
        certificate_media_ids: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            },
            writeOnly: true
        },
        image_media_id: {
            type: 'string',
            format: 'uuid',
            writeOnly: true,
            nullable: true
        }
    },
    required: [
        'fax',
        'name',
        'no_of_rooms',
        'phone'
    ]
} as const;

export const GroupHomeRoomWritableSchema = {
    type: 'object',
    properties: {
        room_number: {
            type: 'string',
            maxLength: 50
        },
        is_active: {
            type: 'boolean'
        },
        is_occupied: {
            type: 'boolean'
        }
    },
    required: [
        'room_number'
    ]
} as const;

export const GroupHomeShiftWritableSchema = {
    type: 'object',
    properties: {
        shift: {
            $ref: '#/components/schemas/ShiftEnum'
        },
        start_time: {
            type: 'string',
            format: 'time'
        },
        end_time: {
            type: 'string',
            format: 'time'
        },
        is_active: {
            type: 'boolean'
        }
    },
    required: [
        'end_time',
        'shift',
        'start_time'
    ]
} as const;

export const GroupHomeUserWritableSchema = {
    type: 'object',
    properties: {
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 255
        },
        phone: {
            type: 'integer',
            maximum: 9223372036854776000,
            minimum: -9223372036854776000,
            format: 'int64',
            nullable: true
        },
        active: {
            type: 'boolean'
        },
        last_login: {
            type: 'string',
            format: 'date-time',
            nullable: true
        }
    },
    required: [
        'email',
        'first_name'
    ]
} as const;

export const IncidentWritableSchema = {
    type: 'object',
    properties: {
        incident_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        resident: {
            type: 'string'
        },
        reported_by: {
            type: 'string',
            nullable: true
        },
        location: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        region: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        received_date: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        incident_datetime: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        agency_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        pre_incident_notes: {
            type: 'string',
            nullable: true
        },
        incident_description: {
            type: 'string',
            nullable: true
        },
        response_action: {
            type: 'string',
            nullable: true
        },
        send_notification: {
            type: 'boolean'
        },
        signature_media_id: {
            type: 'string',
            format: 'uuid',
            writeOnly: true,
            nullable: true
        },
        duplicate_signature_from_profile: {
            type: 'boolean',
            writeOnly: true,
            default: false
        },
        medical_flags: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/IncidentMedicalFlagWritable'
            }
        },
        legal_flags: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/IncidentLegalFlagWritable'
            }
        },
        social_flags: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/IncidentSocialFlagWritable'
            }
        },
        victim_flags: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/IncidentVictimFlagWritable'
            }
        },
        group_home_uuid: {
            type: 'string',
            writeOnly: true,
            nullable: true
        },
        assigned_program_manager_uuid: {
            type: 'string',
            writeOnly: true,
            nullable: true
        },
        program_manager_email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 254
        },
        coordinator_email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 254
        },
        pm_signature_media_id: {
            type: 'string',
            writeOnly: true,
            nullable: true
        },
        pm_review_notes: {
            type: 'string',
            nullable: true
        },
        pm_program_type: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        pm_service_transition: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/PmServiceTransitionEnum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        pm_service_transition_description: {
            type: 'string',
            nullable: true
        },
        pm_behavior_plan_followed: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/PmBehaviorPlanFollowedEnum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        pm_title: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: [
        'resident'
    ]
} as const;

export const IncidentCommentWritableSchema = {
    type: 'object',
    properties: {
        comment: {
            type: 'string'
        }
    },
    required: [
        'comment'
    ]
} as const;

export const IncidentLegalFlagWritableSchema = {
    type: 'object',
    properties: {
        legal_type: {
            type: 'string',
            maxLength: 255
        }
    },
    required: [
        'legal_type'
    ]
} as const;

export const IncidentMedicalFlagWritableSchema = {
    type: 'object',
    properties: {
        medical_type: {
            type: 'string',
            maxLength: 255
        },
        medical_other_details: {
            type: 'string'
        }
    },
    required: [
        'medical_type'
    ]
} as const;

export const IncidentNotificationWritableSchema = {
    type: 'object',
    properties: {
        incident: {
            type: 'integer'
        },
        type: {
            $ref: '#/components/schemas/IncidentNotificationTypeEnum'
        },
        notify: {
            type: 'boolean'
        },
        notify_date: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        notify_time: {
            type: 'string',
            format: 'time',
            nullable: true
        },
        method_of_contact: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        by_whom: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: [
        'incident',
        'type'
    ]
} as const;

export const IncidentResidentDetailsWritableSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email',
            maxLength: 255
        },
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        }
    },
    required: [
        'email',
        'first_name'
    ]
} as const;

export const IncidentSocialFlagWritableSchema = {
    type: 'object',
    properties: {
        social_type: {
            type: 'string',
            maxLength: 255
        },
        social_other_details: {
            type: 'string'
        }
    },
    required: [
        'social_type'
    ]
} as const;

export const IncidentUserWritableSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email',
            maxLength: 255
        },
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        }
    },
    required: [
        'email',
        'first_name'
    ]
} as const;

export const IncidentVictimFlagWritableSchema = {
    type: 'object',
    properties: {
        victim_type: {
            type: 'string',
            maxLength: 255
        }
    },
    required: [
        'victim_type'
    ]
} as const;

export const LeadWritableSchema = {
    type: 'object',
    properties: {
        user: {
            type: 'integer'
        },
        guardian: {
            type: 'integer',
            nullable: true
        },
        agent: {
            type: 'integer',
            nullable: true
        },
        guardian_relation: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        address: {
            type: 'integer',
            nullable: true
        },
        date_of_birth: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        gender: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/GenderEnum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        referral_source: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        status: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/Status7b0Enum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        reason: {
            type: 'string',
            nullable: true
        }
    },
    required: [
        'user'
    ]
} as const;

export const LeadCreateWritableSchema = {
    type: 'object',
    properties: {
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            maxLength: 255
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true
        },
        phone: {
            type: 'integer',
            nullable: true
        },
        guardian: {
            $ref: '#/components/schemas/GuardianCreate'
        },
        guardian_uuid: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        agent: {
            $ref: '#/components/schemas/AgentCreate'
        },
        agent_uuid: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        address: {
            $ref: '#/components/schemas/AddressWritable'
        },
        date_of_birth: {
            type: 'string',
            format: 'date'
        },
        gender: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/GenderEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        referral_source: {
            type: 'string',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/Status7b0Enum'
        },
        guardian_relation: {
            type: 'string',
            nullable: true
        },
        documents_checklist_complete: {
            type: 'boolean',
            default: false
        },
        insurance: {
            $ref: '#/components/schemas/InsuranceCreate'
        }
    },
    required: [
        'first_name',
        'last_name'
    ]
} as const;

export const LeadDetailWritableSchema = {
    type: 'object',
    properties: {
        guardian_relation: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        date_of_birth: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        gender: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/GenderEnum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        referral_source: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        status: {
            nullable: true,
            oneOf: [
                {
                    $ref: '#/components/schemas/Status7b0Enum'
                },
                {
                    $ref: '#/components/schemas/BlankEnum'
                },
                {
                    $ref: '#/components/schemas/NullEnum'
                }
            ]
        },
        reason: {
            type: 'string',
            nullable: true
        },
        user: {
            type: 'integer'
        },
        guardian: {
            type: 'integer',
            nullable: true
        },
        agent: {
            type: 'integer',
            nullable: true
        },
        address: {
            type: 'integer',
            nullable: true
        }
    },
    required: [
        'user'
    ]
} as const;

export const LicenseWritableSchema = {
    type: 'object',
    properties: {
        number: {
            type: 'string',
            maxLength: 255
        },
        start_date: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        expiry_date: {
            type: 'string',
            format: 'date-time',
            nullable: true
        }
    },
    required: [
        'number'
    ]
} as const;

export const LoginWritableSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email'
        },
        password: {
            type: 'string',
            writeOnly: true
        }
    },
    required: [
        'email',
        'password'
    ]
} as const;

export const MediaListWritableSchema = {
    type: 'object',
    description: 'Lighter serializer for list views',
    properties: {
        original_filename: {
            type: 'string',
            maxLength: 255
        },
        file_type: {
            $ref: '#/components/schemas/FileTypeEnum'
        },
        mime_type: {
            type: 'string',
            maxLength: 100
        },
        file_extension: {
            type: 'string',
            maxLength: 10
        },
        file_size: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0,
            description: 'File size in bytes'
        },
        width: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0,
            nullable: true,
            description: 'Image width in pixels'
        },
        height: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0,
            nullable: true,
            description: 'Image height in pixels'
        },
        alt_text: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        status: {
            $ref: '#/components/schemas/Status71dEnum'
        },
        metadata: {
            description: 'Extra metadata like signing info'
        },
        uploaded_by: {
            type: 'integer',
            nullable: true
        }
    },
    required: [
        'file_extension',
        'file_size',
        'file_type',
        'mime_type',
        'original_filename'
    ]
} as const;

export const MediaMinimalWritableSchema = {
    type: 'object',
    properties: {
        original_filename: {
            type: 'string',
            maxLength: 255
        },
        file_type: {
            $ref: '#/components/schemas/FileTypeEnum'
        },
        mime_type: {
            type: 'string',
            maxLength: 100
        },
        file_extension: {
            type: 'string',
            maxLength: 10
        },
        file_size: {
            type: 'integer',
            maximum: 2147483647,
            minimum: 0,
            description: 'File size in bytes'
        },
        alt_text: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        description: {
            type: 'string',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/Status71dEnum'
        },
        metadata: {
            description: 'Extra metadata like signing info'
        }
    },
    required: [
        'file_extension',
        'file_size',
        'file_type',
        'mime_type',
        'original_filename'
    ]
} as const;

export const PaginatedMediaListListWritableSchema = {
    type: 'object',
    required: [
        'count',
        'results'
    ],
    properties: {
        count: {
            type: 'integer',
            example: 123
        },
        next: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=4'
        },
        previous: {
            type: 'string',
            nullable: true,
            format: 'uri',
            example: 'http://api.example.org/accounts/?page=2'
        },
        results: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/MediaListWritable'
            }
        }
    }
} as const;

export const PatchedChangePasswordWritableSchema = {
    type: 'object',
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid'
        },
        current_password: {
            type: 'string',
            writeOnly: true
        },
        new_password: {
            type: 'string',
            writeOnly: true,
            minLength: 8
        }
    }
} as const;

export const PatchedUserWritableSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            maxLength: 150
        },
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 255
        },
        phone: {
            type: 'integer',
            maximum: 9223372036854776000,
            minimum: -9223372036854776000,
            format: 'int64',
            nullable: true
        },
        ssn: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        npi: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        active: {
            type: 'boolean'
        }
    }
} as const;

export const ProviderWritableSchema = {
    type: 'object',
    description: 'Full serializer for create / update / retrieve operations.\nAccepts `lead_uuid` on write; exposes it on read.',
    properties: {
        lead_uuid: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        name: {
            type: 'string',
            maxLength: 255
        },
        specialty: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        email: {
            type: 'string',
            format: 'email',
            nullable: true,
            maxLength: 254
        },
        address: {
            type: 'string',
            nullable: true
        },
        phone_number: {
            type: 'string',
            nullable: true,
            maxLength: 30
        },
        fax_number: {
            type: 'string',
            nullable: true,
            maxLength: 30
        }
    },
    required: [
        'name'
    ]
} as const;

export const RegisterWritableSchema = {
    type: 'object',
    description: 'Username is generated by the backend (random); do not send from client.',
    properties: {
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            maxLength: 255
        },
        email: {
            type: 'string',
            format: 'email'
        },
        phone: {
            type: 'integer',
            nullable: true
        },
        ssn: {
            type: 'string',
            nullable: true
        },
        npi: {
            type: 'string',
            nullable: true
        },
        role_name: {
            type: 'string',
            writeOnly: true
        },
        group_home_uuid: {
            type: 'string',
            writeOnly: true,
            nullable: true
        }
    },
    required: [
        'email',
        'first_name',
        'last_name',
        'role_name'
    ]
} as const;

export const RoleWritableSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            maxLength: 255
        },
        type: {
            type: 'string',
            maxLength: 50
        }
    },
    required: [
        'name',
        'type'
    ]
} as const;

export const UserWritableSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            maxLength: 150
        },
        first_name: {
            type: 'string',
            maxLength: 255
        },
        last_name: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 255
        },
        phone: {
            type: 'integer',
            maximum: 9223372036854776000,
            minimum: -9223372036854776000,
            format: 'int64',
            nullable: true
        },
        ssn: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        npi: {
            type: 'string',
            nullable: true,
            maxLength: 255
        },
        active: {
            type: 'boolean'
        }
    },
    required: [
        'email',
        'first_name',
        'username'
    ]
} as const;
