// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8000' | (string & {});
};

export type Address = {
    readonly uuid: string;
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    zipcode?: string | null;
    country?: string | null;
};

export type AgentCreate = {
    first_name: string;
    last_name: string;
    phone?: string | null;
    email: string;
};

export type Appointment = {
    readonly uuid: string;
    lead?: number | null;
    lead_uuid?: string;
    readonly referral_number: string;
    readonly resident_name: string;
    readonly avatar_url: string;
    readonly resident_status: string;
    appointment_title?: string | null;
    description?: string | null;
    appointment_date?: string | null;
    appointment_time?: string | null;
    contact_type?: ContactTypeEnum | BlankEnum | NullEnum | null;
    contact_name?: string | null;
    contact_email?: string | null;
    status?: AppointmentStatusEnum;
    lead_detail: LeadDetail;
    readonly media: Array<MediaMinimal>;
    readonly room: string;
    readonly group_home: string;
    readonly created_by: number | null;
    readonly created_by_email: string;
    readonly created_by_name: string;
    readonly created_at: string | null;
    readonly updated_at: string | null;
    deleted_at?: string | null;
    action_note?: string | null;
    readonly action_by: number | null;
    readonly action_at: string | null;
};

/**
 * * `REQUESTED` - Requested
 * * `COMPLETED` - Completed
 * * `CANCELLED` - Cancelled
 */
export type AppointmentStatusEnum = 'REQUESTED' | 'COMPLETED' | 'CANCELLED';

export type AssignmentCarePlanItemShift = {
    shift: ShiftEnum;
};

export type BlankEnum = '';

/**
 * Serializer for ADL / Daily Tracking Goal logs
 * POST = UPSERT
 * Uniqueness:
 * (care_plan_item + resident + log_date + shift)
 */
export type CarePlanDailyLog = {
    readonly uuid: string;
    care_plan_item_uuid: string;
    resident_uuid: string;
    log_date: string;
    shift: ShiftEnum;
    status: CarePlanDailyLogStatusEnum;
    note?: string | null;
    created_by?: number | null;
    readonly created_at: string;
    readonly updated_at: string;
};

/**
 * * `WORKED` - Worked
 * * `DID_NOT_WORK` - Did Not Work
 * * `COULD_NOT_WORK` - Could Not Work
 */
export type CarePlanDailyLogStatusEnum = 'WORKED' | 'DID_NOT_WORK' | 'COULD_NOT_WORK';

export type CarePlanItem = {
    readonly uuid: string;
    resident: string;
    type: Type094Enum;
    title?: string | null;
    description?: string | null;
    created_by?: string | null;
    readonly assigned_shifts: string;
    readonly is_archived: string;
    readonly created_at: string;
    readonly updated_at: string;
};

export type CarePlanItemList = {
    readonly uuid: string;
    type: Type094Enum;
    title?: string | null;
    description?: string | null;
    readonly assigned_shifts: string;
    readonly daily_status: string;
    readonly monthly_progress: string;
    readonly created_by_details: string;
    readonly updated_by_details: string;
    readonly is_archived: string;
    readonly created_at: string;
    readonly updated_at: string;
    deleted_at?: string | null;
};

export type CarePlanReport = {
    readonly uuid: string;
    resident_uuid: string;
    report_month: number;
    report_year: number;
    report_data: unknown;
    readonly generated_by: number | null;
    readonly pdf_url: string;
    readonly created_at: string;
    readonly updated_at: string;
};

export type CompleteOnboarding = {
    group_home: string;
    room?: string | null;
    check_in_date: string;
};

export type ConsentFormCreate = {
    resident_uuid: string;
    form_name: string;
    form_code: string;
    frequency_type: string;
    status: ConsentFormCreateStatusEnum;
    form_json?: unknown;
    signer_type?: string | null;
    next_due_at?: string | null;
};

/**
 * * `DRAFT` - DRAFT
 * * `COMPLETED` - COMPLETED
 * * `SIGNED` - SIGNED
 */
export type ConsentFormCreateStatusEnum = 'DRAFT' | 'COMPLETED' | 'SIGNED';

export type ConsentFormEntry = {
    readonly uuid: string;
    readonly form_uuid: string;
    version: string;
    form_json: unknown;
    filled_at?: string | null;
    next_due_at?: string | null;
    status: ConsentFormEntryStatusEnum;
    created_at?: string;
    updated_at?: string | null;
};

/**
 * * `DRAFT` - Draft
 * * `COMPLETED` - Completed
 * * `SIGNED` - Signed
 */
export type ConsentFormEntryStatusEnum = 'DRAFT' | 'COMPLETED' | 'SIGNED';

export type ConsentFormShare = {
    recipient_email: string;
    recipient_name: string;
    media_uuid?: string | null;
    /**
     * HTML string to convert to PDF on the server. If provided, backend generates PDF, uploads to S3, and creates a Media record automatically.
     */
    html_content?: string | null;
    /**
     * Portal role to share with. Stamps ConsentForm.signer_type so the document is visible ONLY in the matching portal.
     *
     * * `GUARDIAN` - Guardian
     * * `AGENT` - Agent
     */
    recipient_type?: RecipientTypeEnum | NullEnum | null;
};

/**
 * * `PROVIDER` - Provider
 * * `GUARDIAN` - Guardian
 * * `OTHER` - Other
 */
export type ContactTypeEnum = 'PROVIDER' | 'GUARDIAN' | 'OTHER';

/**
 * * `image` - Image
 * * `document` - Document
 * * `video` - Video
 * * `audio` - Audio
 * * `other` - Other
 */
export type FileTypeEnum = 'image' | 'document' | 'video' | 'audio' | 'other';

/**
 * * `MALE` - Male
 * * `FEMALE` - Female
 * * `OTHER` - Other
 * * `UNKNOWN` - Unknown
 */
export type GenderEnum = 'MALE' | 'FEMALE' | 'OTHER' | 'UNKNOWN';

export type GroupHome = {
    readonly uuid: string;
    name: string;
    timezone?: TimezoneEnum | BlankEnum | NullEnum | null;
    phone: string;
    fax: string;
    email?: string | null;
    emergency_contact_number?: string | null;
    address?: Address;
    license?: License;
    no_of_rooms: number;
    active?: boolean;
    shifts?: Array<GroupHomeShift>;
    readonly rooms: Array<GroupHomeRoom>;
    readonly media: string;
    readonly avatar_url: string;
    readonly created_at: string | null;
    readonly updated_at: string | null;
};

export type GroupHomeRoom = {
    readonly uuid: string;
    room_number: string;
    is_active?: boolean;
    is_occupied?: boolean;
};

export type GroupHomeShift = {
    readonly uuid: string;
    shift: ShiftEnum;
    start_time: string;
    end_time: string;
    is_active?: boolean;
};

export type GroupHomeStatus = {
    active?: boolean;
};

export type GroupHomeUser = {
    readonly uuid: string;
    first_name: string;
    last_name?: string | null;
    email: string;
    phone?: number | null;
    readonly role: string;
    active?: boolean;
    last_login?: string | null;
};

export type GuardianCreate = {
    first_name: string;
    last_name: string;
    phone?: string | null;
    email: string;
};

export type Incident = {
    readonly uuid: string;
    incident_name?: string | null;
    resident: string;
    readonly resident_uuid: string;
    reported_by?: string | null;
    location?: string | null;
    region?: string | null;
    received_date?: string | null;
    incident_datetime?: string | null;
    agency_name?: string | null;
    pre_incident_notes?: string | null;
    incident_description?: string | null;
    response_action?: string | null;
    send_notification?: boolean;
    status: IncidentStatusEnum;
    readonly lead_uuid: string;
    readonly referral_number: string;
    readonly signature_url: string;
    resident_details: IncidentResidentDetails;
    readonly resident_status: string;
    reported_by_details: IncidentUser;
    readonly notifications: Array<IncidentNotification>;
    readonly comments: Array<IncidentComment>;
    medical_flags?: Array<IncidentMedicalFlag>;
    legal_flags?: Array<IncidentLegalFlag>;
    social_flags?: Array<IncidentSocialFlag>;
    victim_flags?: Array<IncidentVictimFlag>;
    readonly signature: string;
    readonly group_home: string;
    readonly assigned_program_manager: string;
    program_manager_email?: string | null;
    coordinator_email?: string | null;
    readonly reporter_signature_url: string;
    readonly pm_signature_url: string;
    readonly pm_signature: string;
    readonly started_at: string | null;
    readonly submitted_for_review_at: string | null;
    readonly completed_at: string | null;
    pm_review_notes?: string | null;
    pm_program_type?: string | null;
    pm_service_transition?: PmServiceTransitionEnum | BlankEnum | NullEnum | null;
    pm_service_transition_description?: string | null;
    pm_behavior_plan_followed?: PmBehaviorPlanFollowedEnum | BlankEnum | NullEnum | null;
    pm_title?: string | null;
    readonly edits: string;
    created_at?: string;
    readonly updated_at: string;
};

export type IncidentComment = {
    readonly uuid: string;
    comment: string;
    readonly role_name: string;
    readonly created_by_name: string;
    readonly created_at: string;
};

export type IncidentLegalFlag = {
    readonly uuid: string;
    legal_type: string;
};

export type IncidentMedicalFlag = {
    readonly uuid: string;
    medical_type: string;
    medical_other_details?: string;
};

export type IncidentNotification = {
    readonly uuid: string;
    incident: number;
    type: IncidentNotificationTypeEnum;
    readonly user: number | null;
    readonly user_name: string;
    readonly user_email: string;
    notify?: boolean;
    notify_date?: string | null;
    notify_time?: string | null;
    method_of_contact?: string | null;
    by_whom?: string | null;
    created_at?: string;
    readonly updated_at: string;
};

/**
 * * `STAFF` - Staff
 * * `SERVICE_COORDINATOR` - Service Coordinator
 * * `PROGRAM_MANAGER` - Program Manager
 * * `GUARDIAN` - Guardian
 * * `AGENT` - Agent
 * * `NURSING` - Nursing
 * * `ADDITIONAL_SERVICE_PROVIDER` - Additional Service Provider
 */
export type IncidentNotificationTypeEnum = 'STAFF' | 'SERVICE_COORDINATOR' | 'PROGRAM_MANAGER' | 'GUARDIAN' | 'AGENT' | 'NURSING' | 'ADDITIONAL_SERVICE_PROVIDER';

export type IncidentResidentDetails = {
    readonly uuid: string;
    email: string;
    first_name: string;
    last_name?: string | null;
    readonly avatar_url: string;
    readonly lead_uuid: string;
    readonly group_home: string;
    readonly date_of_birth: string;
};

export type IncidentSocialFlag = {
    readonly uuid: string;
    social_type: string;
    social_other_details?: string;
};

/**
 * * `DRAFT` - Draft
 * * `IN_PROGRESS` - In Progress
 * * `PM_REVIEW_PENDING` - Program Manager Review Pending
 * * `COMPLETED` - Completed
 * * `ACKNOWLEDGED` - Acknowledged
 */
export type IncidentStatusEnum = 'DRAFT' | 'IN_PROGRESS' | 'PM_REVIEW_PENDING' | 'COMPLETED' | 'ACKNOWLEDGED';

export type IncidentUser = {
    readonly uuid: string;
    email: string;
    first_name: string;
    last_name?: string | null;
    readonly avatar_url: string;
    readonly role: string;
};

export type IncidentVictimFlag = {
    readonly uuid: string;
    victim_type: string;
};

export type InsuranceCreate = {
    provider?: string | null;
    policy_number?: string | null;
    status?: boolean | null;
};

export type Lead = {
    readonly uuid: string;
    readonly referral_number: string;
    user: number;
    guardian?: number | null;
    agent?: number | null;
    guardian_relation?: string | null;
    address?: number | null;
    date_of_birth?: string | null;
    gender?: GenderEnum | BlankEnum | NullEnum | null;
    referral_source?: string | null;
    status?: Status7B0Enum | BlankEnum | NullEnum | null;
    reason?: string | null;
    readonly created_at: string | null;
    readonly updated_at: string | null;
};

export type LeadCreate = {
    first_name: string;
    last_name: string;
    email?: string | null;
    phone?: number | null;
    guardian?: GuardianCreate;
    guardian_uuid?: string | null;
    agent?: AgentCreate;
    agent_uuid?: string | null;
    address?: Address;
    date_of_birth?: string;
    gender?: GenderEnum | NullEnum | null;
    referral_source?: string | null;
    status?: Status7B0Enum;
    guardian_relation?: string | null;
    documents_checklist_complete?: boolean;
    insurance?: InsuranceCreate;
};

export type LeadDetail = {
    guardian_relation?: string | null;
    readonly uuid: string;
    date_of_birth?: string | null;
    gender?: GenderEnum | BlankEnum | NullEnum | null;
    referral_source?: string | null;
    status?: Status7B0Enum | BlankEnum | NullEnum | null;
    reason?: string | null;
    readonly created_at: string | null;
    readonly updated_at: string | null;
    user: number;
    guardian?: number | null;
    agent?: number | null;
    address?: number | null;
};

export type License = {
    readonly uuid: string;
    number: string;
    start_date?: string | null;
    expiry_date?: string | null;
    readonly created_at: string | null;
    readonly updated_at: string | null;
};

export type Login = {
    email: string;
};

/**
 * Serializer for retrieving media information
 */
export type Media = {
    readonly id: string;
    readonly file_url: string;
    readonly original_filename: string;
    file_type: FileTypeEnum;
    readonly mime_type: string;
    readonly file_extension: string;
    /**
     * File size in bytes
     */
    readonly file_size: number;
    /**
     * Image width in pixels
     */
    readonly width: number | null;
    /**
     * Image height in pixels
     */
    readonly height: number | null;
    readonly alt_text: string | null;
    readonly description: string | null;
    status: Status71dEnum;
    /**
     * Extra metadata like signing info
     */
    readonly metadata: unknown;
    readonly signed: string;
    readonly uploaded_by: string;
    readonly uploaded_at: string;
    readonly updated_at: string;
};

/**
 * Lighter serializer for list views
 */
export type MediaList = {
    readonly id: string;
    readonly file_url: string;
    original_filename: string;
    file_type: FileTypeEnum;
    mime_type: string;
    file_extension: string;
    /**
     * File size in bytes
     */
    file_size: number;
    /**
     * Image width in pixels
     */
    width?: number | null;
    /**
     * Image height in pixels
     */
    height?: number | null;
    alt_text?: string | null;
    readonly description: string;
    status?: Status71dEnum;
    /**
     * Extra metadata like signing info
     */
    metadata?: unknown;
    uploaded_by?: number | null;
    readonly uploaded_at: string;
    readonly updated_at: string;
};

export type MediaMinimal = {
    readonly id: string;
    readonly file_url: string;
    original_filename: string;
    file_type: FileTypeEnum;
    mime_type: string;
    file_extension: string;
    /**
     * File size in bytes
     */
    file_size: number;
    alt_text?: string | null;
    description?: string | null;
    status?: Status71dEnum;
    /**
     * Extra metadata like signing info
     */
    metadata?: unknown;
    readonly uploaded_at: string;
};

export type NullEnum = unknown;

export type PaginatedMediaListList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<MediaList>;
};

export type PatchedChangePassword = {
    uuid?: string;
};

export type PatchedGroupHomeStatus = {
    active?: boolean;
};

export type PatchedMoveOut = {
    check_out_date?: string;
    reason?: string | null;
};

export type PatchedRejectReferral = {
    /**
     * Reason for rejecting the referral
     */
    reason?: string;
};

export type PatchedUser = {
    readonly uuid?: string;
    username?: string;
    first_name?: string;
    last_name?: string | null;
    email?: string;
    phone?: number | null;
    ssn?: string | null;
    npi?: string | null;
    active?: boolean;
    role?: Role;
    readonly group_home?: string;
    readonly group_homes?: string;
    readonly avatar_url?: string;
    readonly signature_url?: string;
    readonly signature_alt_text?: string;
    readonly isPasswordSet?: string;
    readonly permissions?: string;
};

/**
 * * `YES` - Yes
 * * `NO` - No
 * * `N_A` - N/A
 */
export type PmBehaviorPlanFollowedEnum = 'YES' | 'NO' | 'N_A';

/**
 * * `YES` - Yes
 * * `NO` - No
 */
export type PmServiceTransitionEnum = 'YES' | 'NO';

/**
 * Full serializer for create / update / retrieve operations.
 * Accepts `lead_uuid` on write; exposes it on read.
 */
export type Provider = {
    readonly uuid: string;
    lead_uuid?: string | null;
    name: string;
    specialty?: string | null;
    email?: string | null;
    address?: string | null;
    phone_number?: string | null;
    fax_number?: string | null;
    readonly created_by: number | null;
    readonly created_by_name: string;
    readonly created_at: string;
    readonly updated_at: string;
};

export type ReAdmit = {
    status?: ReAdmitStatusEnum;
    room: string;
    group_home_uuid: string;
    check_in_date: string;
    financial_effective_date?: string | null;
};

/**
 * * `ACTIVE` - ACTIVE
 * * `ASSIGNED` - ASSIGNED
 */
export type ReAdmitStatusEnum = 'ACTIVE' | 'ASSIGNED';

/**
 * * `GUARDIAN` - Guardian
 * * `AGENT` - Agent
 */
export type RecipientTypeEnum = 'GUARDIAN' | 'AGENT';

/**
 * Username is generated by the backend (random); do not send from client.
 */
export type Register = {
    first_name: string;
    last_name: string;
    email: string;
    phone?: number | null;
    ssn?: string | null;
    npi?: string | null;
};

export type Role = {
    readonly uuid: string;
    name: string;
    type: string;
};

/**
 * Role with its full permission list — used in admin settings view.
 */
export type RoleWithPermissions = {
    readonly uuid: string;
    readonly name: string;
    readonly type: string;
    readonly description: string | null;
    readonly permissions: string;
};

export type SetPassword = {
    password: string;
};

/**
 * * `MORNING` - Morning
 * * `EVENING` - Evening
 * * `NIGHT` - Night
 */
export type ShiftEnum = 'MORNING' | 'EVENING' | 'NIGHT';

/**
 * * `active` - Active
 * * `deleted` - Deleted
 * * `archived` - Archived
 */
export type Status71dEnum = 'active' | 'deleted' | 'archived';

/**
 * * `DRAFT` - Draft
 * * `UNDER_REVIEW` - Under Review
 * * `DOCS_PENDING` - Docs Pending
 * * `ONBOARDING_IN_PROGRESS` - Onboarding In Progress
 * * `COMPLETED` - Completed
 * * `REJECTED` - Rejected
 */
export type Status7B0Enum = 'DRAFT' | 'UNDER_REVIEW' | 'DOCS_PENDING' | 'ONBOARDING_IN_PROGRESS' | 'COMPLETED' | 'REJECTED';

/**
 * * `Eastern Time` - Eastern Time
 * * `Central Time` - Central Time
 * * `Mountain Time` - Mountain Time
 * * `Pacific Time` - Pacific Time
 * * `Arizona Time` - Arizona Time
 * * `Alaska Time` - Alaska Time
 */
export type TimezoneEnum = 'Eastern Time' | 'Central Time' | 'Mountain Time' | 'Pacific Time' | 'Arizona Time' | 'Alaska Time';

export type TransferResident = {
    group_home: string;
    room?: string | null;
    check_in_date: string;
};

/**
 * * `ADL` - ADL
 * * `GOAL` - Goal
 */
export type Type094Enum = 'ADL' | 'GOAL';

export type User = {
    readonly uuid: string;
    username: string;
    first_name: string;
    last_name?: string | null;
    email: string;
    phone?: number | null;
    ssn?: string | null;
    npi?: string | null;
    active?: boolean;
    role: Role;
    readonly group_home: string;
    readonly group_homes: string;
    readonly avatar_url: string;
    readonly signature_url: string;
    readonly signature_alt_text: string;
    readonly isPasswordSet: string;
    readonly permissions: string;
};

export type VerifyOtp = {
    email: string;
    otp: string;
};

export type AddressWritable = {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    zipcode?: string | null;
    country?: string | null;
};

export type AppointmentWritable = {
    lead?: number | null;
    lead_uuid?: string;
    appointment_title?: string | null;
    description?: string | null;
    appointment_date?: string | null;
    appointment_time?: string | null;
    contact_type?: ContactTypeEnum | BlankEnum | NullEnum | null;
    contact_name?: string | null;
    contact_email?: string | null;
    status?: AppointmentStatusEnum;
    deleted_at?: string | null;
    action_note?: string | null;
};

/**
 * Serializer for ADL / Daily Tracking Goal logs
 * POST = UPSERT
 * Uniqueness:
 * (care_plan_item + resident + log_date + shift)
 */
export type CarePlanDailyLogWritable = {
    care_plan_item_uuid: string;
    resident_uuid: string;
    log_date: string;
    shift: ShiftEnum;
    status: CarePlanDailyLogStatusEnum;
    note?: string | null;
    created_by?: number | null;
};

export type CarePlanItemWritable = {
    resident: string;
    type: Type094Enum;
    title?: string | null;
    description?: string | null;
    created_by?: string | null;
    shifts?: Array<AssignmentCarePlanItemShift>;
};

export type CarePlanItemListWritable = {
    type: Type094Enum;
    title?: string | null;
    description?: string | null;
    deleted_at?: string | null;
};

export type CarePlanReportWritable = {
    resident_uuid: string;
    report_month: number;
    report_year: number;
    report_data: unknown;
};

export type ConsentFormEntryWritable = {
    version: string;
    form_json: unknown;
    filled_at?: string | null;
    next_due_at?: string | null;
    status: ConsentFormEntryStatusEnum;
    created_at?: string;
    updated_at?: string | null;
};

export type GroupHomeWritable = {
    name: string;
    timezone?: TimezoneEnum | BlankEnum | NullEnum | null;
    phone: string;
    fax: string;
    email?: string | null;
    emergency_contact_number?: string | null;
    address?: AddressWritable;
    license?: LicenseWritable;
    no_of_rooms: number;
    active?: boolean;
    shifts?: Array<GroupHomeShiftWritable>;
    certificate_media_ids?: Array<string>;
    image_media_id?: string | null;
};

export type GroupHomeRoomWritable = {
    room_number: string;
    is_active?: boolean;
    is_occupied?: boolean;
};

export type GroupHomeShiftWritable = {
    shift: ShiftEnum;
    start_time: string;
    end_time: string;
    is_active?: boolean;
};

export type GroupHomeUserWritable = {
    first_name: string;
    last_name?: string | null;
    email: string;
    phone?: number | null;
    active?: boolean;
    last_login?: string | null;
};

export type IncidentWritable = {
    incident_name?: string | null;
    resident: string;
    reported_by?: string | null;
    location?: string | null;
    region?: string | null;
    received_date?: string | null;
    incident_datetime?: string | null;
    agency_name?: string | null;
    pre_incident_notes?: string | null;
    incident_description?: string | null;
    response_action?: string | null;
    send_notification?: boolean;
    signature_media_id?: string | null;
    duplicate_signature_from_profile?: boolean;
    medical_flags?: Array<IncidentMedicalFlagWritable>;
    legal_flags?: Array<IncidentLegalFlagWritable>;
    social_flags?: Array<IncidentSocialFlagWritable>;
    victim_flags?: Array<IncidentVictimFlagWritable>;
    group_home_uuid?: string | null;
    assigned_program_manager_uuid?: string | null;
    program_manager_email?: string | null;
    coordinator_email?: string | null;
    pm_signature_media_id?: string | null;
    pm_review_notes?: string | null;
    pm_program_type?: string | null;
    pm_service_transition?: PmServiceTransitionEnum | BlankEnum | NullEnum | null;
    pm_service_transition_description?: string | null;
    pm_behavior_plan_followed?: PmBehaviorPlanFollowedEnum | BlankEnum | NullEnum | null;
    pm_title?: string | null;
    created_at?: string;
};

export type IncidentCommentWritable = {
    comment: string;
};

export type IncidentLegalFlagWritable = {
    legal_type: string;
};

export type IncidentMedicalFlagWritable = {
    medical_type: string;
    medical_other_details?: string;
};

export type IncidentNotificationWritable = {
    incident: number;
    type: IncidentNotificationTypeEnum;
    notify?: boolean;
    notify_date?: string | null;
    notify_time?: string | null;
    method_of_contact?: string | null;
    by_whom?: string | null;
    created_at?: string;
};

export type IncidentResidentDetailsWritable = {
    email: string;
    first_name: string;
    last_name?: string | null;
};

export type IncidentSocialFlagWritable = {
    social_type: string;
    social_other_details?: string;
};

export type IncidentUserWritable = {
    email: string;
    first_name: string;
    last_name?: string | null;
};

export type IncidentVictimFlagWritable = {
    victim_type: string;
};

export type LeadWritable = {
    user: number;
    guardian?: number | null;
    agent?: number | null;
    guardian_relation?: string | null;
    address?: number | null;
    date_of_birth?: string | null;
    gender?: GenderEnum | BlankEnum | NullEnum | null;
    referral_source?: string | null;
    status?: Status7B0Enum | BlankEnum | NullEnum | null;
    reason?: string | null;
};

export type LeadCreateWritable = {
    first_name: string;
    last_name: string;
    email?: string | null;
    phone?: number | null;
    guardian?: GuardianCreate;
    guardian_uuid?: string | null;
    agent?: AgentCreate;
    agent_uuid?: string | null;
    address?: AddressWritable;
    date_of_birth?: string;
    gender?: GenderEnum | NullEnum | null;
    referral_source?: string | null;
    status?: Status7B0Enum;
    guardian_relation?: string | null;
    documents_checklist_complete?: boolean;
    insurance?: InsuranceCreate;
};

export type LeadDetailWritable = {
    guardian_relation?: string | null;
    date_of_birth?: string | null;
    gender?: GenderEnum | BlankEnum | NullEnum | null;
    referral_source?: string | null;
    status?: Status7B0Enum | BlankEnum | NullEnum | null;
    reason?: string | null;
    user: number;
    guardian?: number | null;
    agent?: number | null;
    address?: number | null;
};

export type LicenseWritable = {
    number: string;
    start_date?: string | null;
    expiry_date?: string | null;
};

export type LoginWritable = {
    email: string;
    password: string;
};

/**
 * Lighter serializer for list views
 */
export type MediaListWritable = {
    original_filename: string;
    file_type: FileTypeEnum;
    mime_type: string;
    file_extension: string;
    /**
     * File size in bytes
     */
    file_size: number;
    /**
     * Image width in pixels
     */
    width?: number | null;
    /**
     * Image height in pixels
     */
    height?: number | null;
    alt_text?: string | null;
    status?: Status71dEnum;
    /**
     * Extra metadata like signing info
     */
    metadata?: unknown;
    uploaded_by?: number | null;
};

export type MediaMinimalWritable = {
    original_filename: string;
    file_type: FileTypeEnum;
    mime_type: string;
    file_extension: string;
    /**
     * File size in bytes
     */
    file_size: number;
    alt_text?: string | null;
    description?: string | null;
    status?: Status71dEnum;
    /**
     * Extra metadata like signing info
     */
    metadata?: unknown;
};

export type PaginatedMediaListListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<MediaListWritable>;
};

export type PatchedChangePasswordWritable = {
    uuid?: string;
    current_password?: string;
    new_password?: string;
};

export type PatchedUserWritable = {
    username?: string;
    first_name?: string;
    last_name?: string | null;
    email?: string;
    phone?: number | null;
    ssn?: string | null;
    npi?: string | null;
    active?: boolean;
};

/**
 * Full serializer for create / update / retrieve operations.
 * Accepts `lead_uuid` on write; exposes it on read.
 */
export type ProviderWritable = {
    lead_uuid?: string | null;
    name: string;
    specialty?: string | null;
    email?: string | null;
    address?: string | null;
    phone_number?: string | null;
    fax_number?: string | null;
};

/**
 * Username is generated by the backend (random); do not send from client.
 */
export type RegisterWritable = {
    first_name: string;
    last_name: string;
    email: string;
    phone?: number | null;
    ssn?: string | null;
    npi?: string | null;
    role_name: string;
    group_home_uuid?: string | null;
};

export type RoleWritable = {
    name: string;
    type: string;
};

export type UserWritable = {
    username: string;
    first_name: string;
    last_name?: string | null;
    email: string;
    phone?: number | null;
    ssn?: string | null;
    npi?: string | null;
    active?: boolean;
};

export type AccountsAuthRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/auth/';
};

export type AccountsAuthRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ForgotPasswordSendOtpData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/forgot-password/';
};

export type ForgotPasswordSendOtpResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ResendPasswordOtpData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/forgot-password/resend-otp/';
};

export type ResendPasswordOtpResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type VerifyPasswordOtpData = {
    body: VerifyOtp;
    path?: never;
    query?: never;
    url: '/api/accounts/forgot-password/verify-otp/';
};

export type VerifyPasswordOtpResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type LoginUserData = {
    body: LoginWritable;
    path?: never;
    query?: never;
    url: '/api/accounts/login/';
};

export type LoginUserResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/logout/';
};

export type LogoutResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type RefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/refresh/';
};

export type RefreshTokenResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type RegisterUserData = {
    body: RegisterWritable;
    path?: never;
    query?: never;
    url: '/api/accounts/register/';
};

export type RegisterUserResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ListRolesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Comma separated role types (ADMIN, STAFF)
         */
        type?: string;
    };
    url: '/api/accounts/roles/';
};

export type ListRolesResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type CreateRoleData = {
    body: RoleWritable;
    path?: never;
    query?: never;
    url: '/api/accounts/roles/';
};

export type CreateRoleResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ListRolesPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/roles/permissions/';
};

export type ListRolesPermissionsResponses = {
    200: Array<RoleWithPermissions>;
};

export type ListRolesPermissionsResponse = ListRolesPermissionsResponses[keyof ListRolesPermissionsResponses];

export type SetPasswordData = {
    body: SetPassword;
    path?: never;
    query?: never;
    url: '/api/accounts/set-password';
};

export type SetPasswordResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ChangeUserPasswordData = {
    body?: PatchedChangePasswordWritable;
    path?: never;
    query?: never;
    url: '/api/accounts/user/change-password';
};

export type ChangeUserPasswordResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ResendUserInviteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/accounts/user/resend-invite';
};

export type ResendUserInviteResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter users assigned to a group home (UUID)
         */
        group_home_uuid?: string;
        page?: number;
        /**
         * Comma separated role types (ADMIN,STAFF)
         */
        role?: string;
        /**
         * Search by first name or last name
         */
        search?: string;
        size?: number;
        /**
         * active | inactive | all
         */
        status?: string;
    };
    url: '/api/accounts/users/';
};

export type ListUsersResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type GetUserDetailData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/accounts/users/{uuid}/';
};

export type GetUserDetailResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UpdateUserData = {
    body: UserWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/accounts/users/{uuid}/';
};

export type UpdateUserResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type AccountsUsersCanDeleteRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/accounts/users/{uuid}/can-delete/';
};

export type AccountsUsersCanDeleteRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ChangeUserStatusData = {
    body?: PatchedUserWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/accounts/users/{uuid}/status/';
};

export type ChangeUserStatusResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ListAppointmentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by appointment date (YYYY-MM-DD)
         */
        date?: string;
        /**
         * Filter by active group home ID
         */
        group_home?: number;
        /**
         * Filter appointments by resident (lead) UUID
         */
        lead_uuid?: string;
        /**
         * Page number
         */
        page?: number;
        /**
         * Search by resident first or last name
         */
        search?: string;
        /**
         * Number of records per page
         */
        size?: number;
        /**
         * Filter by appointment status
         */
        status?: string;
        /**
         * Filter appointments by guardian or agent UUID
         */
        user_uuid?: string;
    };
    url: '/api/appointments/';
};

export type ListAppointmentsResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type ListAppointmentsResponse = ListAppointmentsResponses[keyof ListAppointmentsResponses];

export type CreateAppointmentData = {
    body?: AppointmentWritable;
    path?: never;
    query?: never;
    url: '/api/appointments/';
};

export type CreateAppointmentErrors = {
    400: {
        [key: string]: unknown;
    };
    500: {
        [key: string]: unknown;
    };
};

export type CreateAppointmentError = CreateAppointmentErrors[keyof CreateAppointmentErrors];

export type CreateAppointmentResponses = {
    201: Appointment;
};

export type CreateAppointmentResponse = CreateAppointmentResponses[keyof CreateAppointmentResponses];

export type DeleteAppointmentData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/appointments/{uuid}/';
};

export type DeleteAppointmentErrors = {
    404: {
        [key: string]: unknown;
    };
};

export type DeleteAppointmentError = DeleteAppointmentErrors[keyof DeleteAppointmentErrors];

export type DeleteAppointmentResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type DeleteAppointmentResponse = DeleteAppointmentResponses[keyof DeleteAppointmentResponses];

export type GetAppointmentData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/appointments/{uuid}/';
};

export type GetAppointmentErrors = {
    404: {
        [key: string]: unknown;
    };
};

export type GetAppointmentError = GetAppointmentErrors[keyof GetAppointmentErrors];

export type GetAppointmentResponses = {
    200: Appointment;
};

export type GetAppointmentResponse = GetAppointmentResponses[keyof GetAppointmentResponses];

export type UpdateAppointmentData = {
    body?: AppointmentWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/appointments/{uuid}/';
};

export type UpdateAppointmentErrors = {
    400: {
        [key: string]: unknown;
    };
    404: {
        [key: string]: unknown;
    };
};

export type UpdateAppointmentError = UpdateAppointmentErrors[keyof UpdateAppointmentErrors];

export type UpdateAppointmentResponses = {
    200: Appointment;
};

export type UpdateAppointmentResponse = UpdateAppointmentResponses[keyof UpdateAppointmentResponses];

export type UpdateAppointmentStatusData = {
    body?: {
        [key: string]: unknown;
    };
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/appointments/{uuid}/status/';
};

export type UpdateAppointmentStatusErrors = {
    400: {
        [key: string]: unknown;
    };
    404: {
        [key: string]: unknown;
    };
};

export type UpdateAppointmentStatusError = UpdateAppointmentStatusErrors[keyof UpdateAppointmentStatusErrors];

export type UpdateAppointmentStatusResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type UpdateAppointmentStatusResponse = UpdateAppointmentStatusResponses[keyof UpdateAppointmentStatusResponses];

export type ListAuditLogsData = {
    body?: never;
    path?: never;
    query?: {
        action?: string;
        /**
         * YYYY-MM-DD or MM/DD/YYYY
         */
        date?: string;
        entity_type?: string;
        /**
         * Group Home UUID
         */
        group_home?: string;
        page?: number;
        search?: string;
        size?: number;
        /**
         * Filter by target user UUID
         */
        target_user?: string;
    };
    url: '/api/audit-logs/';
};

export type ListAuditLogsResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type CreateConsentFormData = {
    body: ConsentFormCreate;
    path?: never;
    query?: never;
    url: '/api/document/consent-forms/';
};

export type CreateConsentFormResponses = {
    201: ConsentFormEntry;
};

export type CreateConsentFormResponse = CreateConsentFormResponses[keyof CreateConsentFormResponses];

export type DeleteConsentFormData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/document/consent-forms/{uuid}/';
};

export type DeleteConsentFormResponses = {
    /**
     * No response body
     */
    204: void;
};

export type DeleteConsentFormResponse = DeleteConsentFormResponses[keyof DeleteConsentFormResponses];

export type GetConsentFormDetailData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: {
        /**
         * Include full history
         */
        history?: boolean;
    };
    url: '/api/document/consent-forms/{uuid}/';
};

export type GetConsentFormDetailResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UpdateConsentFormData = {
    body?: {
        [key: string]: unknown;
    };
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/document/consent-forms/{uuid}/';
};

export type UpdateConsentFormResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ShareConsentFormData = {
    body: ConsentFormShare;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/document/consent-forms/{uuid}/share/';
};

export type ShareConsentFormResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type ShareConsentFormResponse = ShareConsentFormResponses[keyof ShareConsentFormResponses];

export type ListConsentFormsData = {
    body?: never;
    path?: never;
    query?: {
        resident_uuid?: string;
        search?: string;
        signer_type?: string;
    };
    url: '/api/document/consent-forms/list/';
};

export type ListConsentFormsResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ListGroupHomesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        size?: number;
    };
    url: '/api/group-homes/';
};

export type ListGroupHomesResponses = {
    200: Array<GroupHome>;
};

export type ListGroupHomesResponse = ListGroupHomesResponses[keyof ListGroupHomesResponses];

export type CreateGroupHomeData = {
    body: GroupHomeWritable;
    path?: never;
    query?: never;
    url: '/api/group-homes/';
};

export type CreateGroupHomeResponses = {
    201: GroupHome;
};

export type CreateGroupHomeResponse = CreateGroupHomeResponses[keyof CreateGroupHomeResponses];

export type DeleteGroupHomeData = {
    body?: never;
    path: {
        /**
         * Group Home UUID
         */
        uuid: string;
    };
    query?: never;
    url: '/api/group-homes/{uuid}/';
};

export type DeleteGroupHomeResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type RetrieveGroupHomeData = {
    body?: never;
    path: {
        /**
         * Group Home UUID
         */
        uuid: string;
    };
    query?: never;
    url: '/api/group-homes/{uuid}/';
};

export type RetrieveGroupHomeResponses = {
    200: GroupHome;
};

export type RetrieveGroupHomeResponse = RetrieveGroupHomeResponses[keyof RetrieveGroupHomeResponses];

export type GroupHomesUpdateData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/group-homes/{uuid}/';
};

export type GroupHomesUpdateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type GroupHomesAssignmentsRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/group-homes/{uuid}/assignments/';
};

export type GroupHomesAssignmentsRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type GroupHomesAssignmentsCreateData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/group-homes/{uuid}/assignments/';
};

export type GroupHomesAssignmentsCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type GroupHomesAssignmentsDestroyData = {
    body?: never;
    path: {
        assignment_uuid: string;
        uuid: string;
    };
    query?: never;
    url: '/api/group-homes/{uuid}/assignments/{assignment_uuid}/';
};

export type GroupHomesAssignmentsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type GroupHomesAssignmentsDestroyResponse = GroupHomesAssignmentsDestroyResponses[keyof GroupHomesAssignmentsDestroyResponses];

export type GroupHomesCanDeleteRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/group-homes/{uuid}/can-delete/';
};

export type GroupHomesCanDeleteRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UpdateGroupHomeStatusData = {
    body?: PatchedGroupHomeStatus;
    path: {
        /**
         * Group Home UUID
         */
        uuid: string;
    };
    query?: never;
    url: '/api/group-homes/{uuid}/status';
};

export type UpdateGroupHomeStatusResponses = {
    200: GroupHomeStatus;
};

export type UpdateGroupHomeStatusResponse = UpdateGroupHomeStatusResponses[keyof UpdateGroupHomeStatusResponses];

export type ListGroupHomeUsersData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: {
        /**
         * Filter by active status (true/false)
         */
        active?: boolean;
        /**
         * Page number
         */
        page?: number;
        /**
         * Comma-separated role types: staff,admin,lead,resident,guardian,agent
         */
        role_type?: string;
        /**
         * Page size
         */
        size?: number;
    };
    url: '/api/group-homes/{uuid}/users/';
};

export type ListGroupHomeUsersResponses = {
    200: Array<GroupHomeUser>;
};

export type ListGroupHomeUsersResponse = ListGroupHomeUsersResponses[keyof ListGroupHomeUsersResponses];

export type ListIncidentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by incident date (YYYY-MM-DD)
         */
        date?: string;
        /**
         * If true, returns latest incident per resident
         */
        distinctLatest?: boolean;
        /**
         * Filter incidents by group home uuid
         */
        group_home_uuid?: string;
        page?: number;
        /**
         * Filter incidents by resident UUID
         */
        resident_uuid?: string;
        /**
         * Role context for filtering (ADMIN, GUARDIAN, AGENT)
         */
        role?: string;
        /**
         * Search resident by full name
         */
        search?: string;
        size?: number;
        /**
         * Filter by status (OPEN / CLOSED / ACKNOWLEDGED)
         */
        status?: string;
        /**
         * Guardian or Agent user UUID (required when role is GUARDIAN or AGENT)
         */
        uuid?: string;
    };
    url: '/api/incidents/';
};

export type ListIncidentsResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type CreateIncidentData = {
    body: IncidentWritable;
    path?: never;
    query?: never;
    url: '/api/incidents/';
};

export type CreateIncidentResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type DeleteIncidentData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/incidents/{uuid}/';
};

export type DeleteIncidentResponses = {
    /**
     * No response body
     */
    204: void;
};

export type DeleteIncidentResponse = DeleteIncidentResponses[keyof DeleteIncidentResponses];

export type GetIncidentData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/incidents/{uuid}/';
};

export type GetIncidentResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type PatchIncidentData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/incidents/{uuid}/';
};

export type PatchIncidentResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UpdateIncidentData = {
    body: IncidentWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/incidents/{uuid}/';
};

export type UpdateIncidentResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type IncidentsAcknowledgeCreateData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/incidents/{uuid}/acknowledge/';
};

export type IncidentsAcknowledgeCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type IncidentsPmSignoffCreateData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/incidents/{uuid}/pm-signoff/';
};

export type IncidentsPmSignoffCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type IncidentsSendBackCreateData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/incidents/{uuid}/send-back/';
};

export type IncidentsSendBackCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type IncidentsStartCreateData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/incidents/{uuid}/start/';
};

export type IncidentsStartCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UpdateIncidentStatusData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/incidents/{uuid}/status/';
};

export type UpdateIncidentStatusResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type IncidentsSubmitForReviewCreateData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/incidents/{uuid}/submit-for-review/';
};

export type IncidentsSubmitForReviewCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type IncidentsResidentContextRetrieveData = {
    body?: never;
    path: {
        resident_uuid: string;
    };
    query?: never;
    url: '/api/incidents/resident-context/{resident_uuid}/';
};

export type IncidentsResidentContextRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ListLeadsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Filter leads by referral source
         */
        referral_source?: string;
        /**
         * Search by user name or referral source
         */
        search?: string;
        /**
         * Number of records per page
         */
        size?: number;
        /**
         * Filter leads by status
         */
        status?: string;
    };
    url: '/api/leads/';
};

export type ListLeadsResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type CreateLeadData = {
    body: LeadCreateWritable;
    path?: never;
    query?: never;
    url: '/api/leads/';
};

export type CreateLeadResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type CompleteOnboardingData = {
    body: CompleteOnboarding;
    path: {
        lead_uuid: string;
    };
    query?: never;
    url: '/api/leads/{lead_uuid}/complete-onboarding/';
};

export type CompleteOnboardingResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type CompleteOnboardingResponse = CompleteOnboardingResponses[keyof CompleteOnboardingResponses];

export type GetLeadDetailData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/leads/{uuid}/';
};

export type GetLeadDetailResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type UpdateLeadData = {
    body: LeadWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/leads/{uuid}/';
};

export type UpdateLeadResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type RefreshLeadStatusData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/leads/{uuid}/refresh-status/';
};

export type RefreshLeadStatusErrors = {
    404: {
        [key: string]: unknown;
    };
};

export type RefreshLeadStatusError = RefreshLeadStatusErrors[keyof RefreshLeadStatusErrors];

export type RefreshLeadStatusResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type RefreshLeadStatusResponse = RefreshLeadStatusResponses[keyof RefreshLeadStatusResponses];

export type RejectReferralData = {
    body?: PatchedRejectReferral;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/leads/{uuid}/reject/';
};

export type RejectReferralResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type RejectReferralResponse = RejectReferralResponses[keyof RejectReferralResponses];

export type MoveOutLeadData = {
    body?: PatchedMoveOut;
    path: {
        assignment_uuid: string;
    };
    query?: never;
    url: '/api/leads/assignments/{assignment_uuid}/move-out/';
};

export type MoveOutLeadResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type MoveOutLeadResponse = MoveOutLeadResponses[keyof MoveOutLeadResponses];

export type ReAdmitLeadData = {
    body: ReAdmit;
    path: {
        assignment_uuid: string;
    };
    query?: never;
    url: '/api/leads/assignments/{assignment_uuid}/re-admit/';
};

export type ReAdmitLeadResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type ReAdmitLeadResponse = ReAdmitLeadResponses[keyof ReAdmitLeadResponses];

export type TransferResidentData = {
    body: TransferResident;
    path: {
        assignment_uuid: string;
    };
    query?: never;
    url: '/api/leads/assignments/{assignment_uuid}/transfer/';
};

export type TransferResidentResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type TransferResidentResponse = TransferResidentResponses[keyof TransferResidentResponses];

export type ListResidentsData = {
    body?: never;
    path?: never;
    query?: {
        date?: string;
        group_home?: number;
        leads?: boolean;
        page?: number;
        role?: string;
        search?: string;
        size?: number;
        status?: string;
        user_id?: number;
        user_uuid?: string;
    };
    url: '/api/leads/residents/';
};

export type ListResidentsResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type ListResidentsResponse = ListResidentsResponses[keyof ListResidentsResponses];

export type MediaListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/api/media/';
};

export type MediaListResponses = {
    200: PaginatedMediaListList;
};

export type MediaListResponse = MediaListResponses[keyof MediaListResponses];

export type MediaRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/media/{id}/';
};

export type MediaRetrieveResponses = {
    200: Media;
};

export type MediaRetrieveResponse = MediaRetrieveResponses[keyof MediaRetrieveResponses];

export type MediaDeleteDestroyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/media/{id}/delete/';
};

export type MediaDeleteDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type MediaDeleteDestroyResponse = MediaDeleteDestroyResponses[keyof MediaDeleteDestroyResponses];

export type MediaSignCreateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/media/{id}/sign/';
};

export type MediaSignCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type MediaUpdateUpdateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/media/{id}/update/';
};

export type MediaUpdateUpdateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type MediaConfirmUploadCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/media/confirm-upload/';
};

export type MediaConfirmUploadCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type MediaGenerateUploadUrlCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/media/generate-upload-url/';
};

export type MediaGenerateUploadUrlCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type MediaListListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
    url: '/api/media/list/';
};

export type MediaListListResponses = {
    200: PaginatedMediaListList;
};

export type MediaListListResponse = MediaListListResponses[keyof MediaListListResponses];

export type MediaUploadCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/media/upload/';
};

export type MediaUploadCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ListProvidersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter providers by resident (lead) UUID
         */
        lead_uuid?: string;
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Search by provider name or specialty
         */
        search?: string;
        /**
         * Records per page (default: 10)
         */
        size?: number;
    };
    url: '/api/providers/';
};

export type ListProvidersResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type ListProvidersResponse = ListProvidersResponses[keyof ListProvidersResponses];

export type CreateProviderData = {
    body: ProviderWritable;
    path?: never;
    query?: never;
    url: '/api/providers/';
};

export type CreateProviderErrors = {
    400: {
        [key: string]: unknown;
    };
    500: {
        [key: string]: unknown;
    };
};

export type CreateProviderError = CreateProviderErrors[keyof CreateProviderErrors];

export type CreateProviderResponses = {
    201: Provider;
};

export type CreateProviderResponse = CreateProviderResponses[keyof CreateProviderResponses];

export type DeleteProviderData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/providers/{uuid}/';
};

export type DeleteProviderErrors = {
    404: {
        [key: string]: unknown;
    };
    500: {
        [key: string]: unknown;
    };
};

export type DeleteProviderError = DeleteProviderErrors[keyof DeleteProviderErrors];

export type DeleteProviderResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type DeleteProviderResponse = DeleteProviderResponses[keyof DeleteProviderResponses];

export type GetProviderData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/providers/{uuid}/';
};

export type GetProviderErrors = {
    404: {
        [key: string]: unknown;
    };
};

export type GetProviderError = GetProviderErrors[keyof GetProviderErrors];

export type GetProviderResponses = {
    200: Provider;
};

export type GetProviderResponse = GetProviderResponses[keyof GetProviderResponses];

export type UpdateProviderData = {
    body: ProviderWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/providers/{uuid}/';
};

export type UpdateProviderErrors = {
    400: {
        [key: string]: unknown;
    };
    404: {
        [key: string]: unknown;
    };
    500: {
        [key: string]: unknown;
    };
};

export type UpdateProviderError = UpdateProviderErrors[keyof UpdateProviderErrors];

export type UpdateProviderResponses = {
    200: Provider;
};

export type UpdateProviderResponse = UpdateProviderResponses[keyof UpdateProviderResponses];

export type ResidentsListData = {
    body?: never;
    path?: never;
    query?: {
        archived?: boolean;
        date?: string;
        month?: number;
        resident_uuid?: string;
        search?: string;
        shifts?: string;
        type?: 'ADL' | 'GOAL';
        year?: number;
    };
    url: '/api/residents/';
};

export type ResidentsListResponses = {
    200: Array<CarePlanItemList>;
};

export type ResidentsListResponse = ResidentsListResponses[keyof ResidentsListResponses];

export type ResidentsCreateData = {
    body: CarePlanItemWritable;
    path?: never;
    query?: never;
    url: '/api/residents/';
};

export type ResidentsCreateResponses = {
    200: CarePlanItem;
};

export type ResidentsCreateResponse = ResidentsCreateResponses[keyof ResidentsCreateResponses];

export type ResidentsRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: {
        /**
         * Pass 'history' to get past-to-present daily logs
         */
        view?: 'history';
    };
    url: '/api/residents/{uuid}/';
};

export type ResidentsRetrieveResponses = {
    200: CarePlanItem;
};

export type ResidentsRetrieveResponse = ResidentsRetrieveResponses[keyof ResidentsRetrieveResponses];

export type ResidentsUpdateData = {
    body: CarePlanItemWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/residents/{uuid}/';
};

export type ResidentsUpdateResponses = {
    200: CarePlanItem;
};

export type ResidentsUpdateResponse = ResidentsUpdateResponses[keyof ResidentsUpdateResponses];

export type ResidentsArchiveCreateData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/residents/{uuid}/archive/';
};

export type ResidentsArchiveCreateResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ResidentsArchiveCreateResponse = ResidentsArchiveCreateResponses[keyof ResidentsArchiveCreateResponses];

export type ResidentsCarePlanReportsCreateData = {
    body: CarePlanReportWritable;
    path?: never;
    query?: never;
    url: '/api/residents/care-plan-reports/';
};

export type ResidentsCarePlanReportsCreateResponses = {
    200: CarePlanReport;
};

export type ResidentsCarePlanReportsCreateResponse = ResidentsCarePlanReportsCreateResponses[keyof ResidentsCarePlanReportsCreateResponses];

export type ResidentsCarePlanReportsDestroyData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/residents/care-plan-reports/{uuid}/';
};

export type ResidentsCarePlanReportsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ResidentsCarePlanReportsDestroyResponse = ResidentsCarePlanReportsDestroyResponses[keyof ResidentsCarePlanReportsDestroyResponses];

export type ResidentsCarePlanReportsListData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/residents/care-plan-reports/{uuid}/';
};

export type ResidentsCarePlanReportsListResponses = {
    200: Array<CarePlanReport>;
};

export type ResidentsCarePlanReportsListResponse = ResidentsCarePlanReportsListResponses[keyof ResidentsCarePlanReportsListResponses];

export type ResidentsDailyLogsListData = {
    body?: never;
    path?: never;
    query?: {
        archived?: boolean;
        care_plan_item_uuid?: string;
        date?: string;
        resident_uuid?: string;
    };
    url: '/api/residents/daily-logs/';
};

export type ResidentsDailyLogsListResponses = {
    200: Array<CarePlanDailyLog>;
};

export type ResidentsDailyLogsListResponse = ResidentsDailyLogsListResponses[keyof ResidentsDailyLogsListResponses];

export type ResidentsDailyLogsCreateData = {
    body: CarePlanDailyLogWritable;
    path?: never;
    query?: never;
    url: '/api/residents/daily-logs/';
};

export type ResidentsDailyLogsCreateResponses = {
    200: CarePlanDailyLog;
};

export type ResidentsDailyLogsCreateResponse = ResidentsDailyLogsCreateResponses[keyof ResidentsDailyLogsCreateResponses];

export type ResidentsDailyLogsRetrieveData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/residents/daily-logs/{uuid}/';
};

export type ResidentsDailyLogsRetrieveResponses = {
    200: CarePlanDailyLog;
};

export type ResidentsDailyLogsRetrieveResponse = ResidentsDailyLogsRetrieveResponses[keyof ResidentsDailyLogsRetrieveResponses];

export type ResidentsDailyLogsUpdateData = {
    body: CarePlanDailyLogWritable;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/residents/daily-logs/{uuid}/';
};

export type ResidentsDailyLogsUpdateResponses = {
    200: CarePlanDailyLog;
};

export type ResidentsDailyLogsUpdateResponse = ResidentsDailyLogsUpdateResponses[keyof ResidentsDailyLogsUpdateResponses];

export type ResidentsDailyLogsArchiveCreateData = {
    body?: never;
    path: {
        uuid: string;
    };
    query?: never;
    url: '/api/residents/daily-logs/{uuid}/archive/';
};

export type ResidentsDailyLogsArchiveCreateResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ResidentsDailyLogsArchiveCreateResponse = ResidentsDailyLogsArchiveCreateResponses[keyof ResidentsDailyLogsArchiveCreateResponses];

export type ResidentsDailyLogsArchivedListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/residents/daily-logs/archived/';
};

export type ResidentsDailyLogsArchivedListResponses = {
    200: Array<CarePlanDailyLog>;
};

export type ResidentsDailyLogsArchivedListResponse = ResidentsDailyLogsArchivedListResponses[keyof ResidentsDailyLogsArchivedListResponses];

export type ResidentsResidentScheduledFormsRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/residents/resident-scheduled-forms/';
};

export type ResidentsResidentScheduledFormsRetrieveResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ResidentsResidentScheduledFormsCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/residents/resident-scheduled-forms/';
};

export type ResidentsResidentScheduledFormsCreateResponses = {
    /**
     * No response body
     */
    200: unknown;
};

export type ResidentsResidentScheduledFormsDestroyData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/residents/resident-scheduled-forms/{id}/';
};

export type ResidentsResidentScheduledFormsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ResidentsResidentScheduledFormsDestroyResponse = ResidentsResidentScheduledFormsDestroyResponses[keyof ResidentsResidentScheduledFormsDestroyResponses];

export type SchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'af' | 'ar' | 'ar-dz' | 'ast' | 'az' | 'be' | 'bg' | 'bn' | 'br' | 'bs' | 'ca' | 'ckb' | 'cs' | 'cy' | 'da' | 'de' | 'dsb' | 'el' | 'en' | 'en-au' | 'en-gb' | 'eo' | 'es' | 'es-ar' | 'es-co' | 'es-mx' | 'es-ni' | 'es-ve' | 'et' | 'eu' | 'fa' | 'fi' | 'fr' | 'fy' | 'ga' | 'gd' | 'gl' | 'he' | 'hi' | 'hr' | 'hsb' | 'ht' | 'hu' | 'hy' | 'ia' | 'id' | 'ig' | 'io' | 'is' | 'it' | 'ja' | 'ka' | 'kab' | 'kk' | 'km' | 'kn' | 'ko' | 'ky' | 'lb' | 'lt' | 'lv' | 'mk' | 'ml' | 'mn' | 'mr' | 'ms' | 'my' | 'nb' | 'ne' | 'nl' | 'nn' | 'os' | 'pa' | 'pl' | 'pt' | 'pt-br' | 'ro' | 'ru' | 'sk' | 'sl' | 'sq' | 'sr' | 'sr-latn' | 'sv' | 'sw' | 'ta' | 'te' | 'tg' | 'th' | 'tk' | 'tr' | 'tt' | 'udm' | 'ug' | 'uk' | 'ur' | 'uz' | 'vi' | 'zh-hans' | 'zh-hant';
    };
    url: '/api/schema/';
};

export type SchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SchemaRetrieveResponse = SchemaRetrieveResponses[keyof SchemaRetrieveResponses];
